### ISSUE TITLE
app not working

### ISSUE THREAD

**Issue by aarush-paul** [miroslavpejic85/mirotalksfu#10]
hello @miroslavpejic85, i opened up mirotalksfu.ddns,net on two devices, but the participant's video keeps on loading. pls help me out

**Comment by Jaideep25** [comment]
Please press ctrl+shift+j and send a screenshot :) Thanks! ;)

**Comment by Jaideep25** [comment]
@aarush-paul  and could you please tell how did you host it on ddns.net? Maybe their some problem?

**Comment by aarush-paul** [comment]
Actually I didn't host it, it was hosted by the author itself (refer to description)

**Comment by Jaideep25** [comment]
Oh, so from that itself it isn't working, could you show the error in the console? And tell the browser with it's version? ;)

**Comment by aarush-paul** [comment]
Sure
I'm on chrome v93.0.4577.82

**Comment by Jaideep25** [comment]
And the error in the console?

**Comment by miroslavpejic85** [comment]
Closed due to insufficient information to analyze it

**Comment by JagdishTech** [comment]
Hello I am also getting same issue, 
Setup done via docker on local,
Also added NGROCK

I am attaching screenshot, docker log and console logs. 

![image](https://user-images.githubusercontent.com/89624981/145567016-92411cd1-0497-415a-8a51-37bb2896b327.png)

Console Logs:
Room.js:118 01 ----> init Enumerate Devices
Room.js:152 02 ----> Get Audio Devices
Room.js:175 03 ----> Get Video Devices
Room.js:243 04 ----> Who are you
Room.js:399 05 ----> join to Room 44494RareTiger
RoomClient.js:135 06 ----> Load Mediasoup Client v 3.6.47
RoomClient.js:211 07 ----> Get Router Rtp Capabilities codecs:  Array(9)
RoomClient.js:524 08 ----> Start audio media
RoomClient.js:575 Media contraints audioType: Object
RoomClient.js:530 09 ----> Start video media
RoomClient.js:575 Media contraints videoType: Object
RoomClient.js:417 New producers Array(2)
RoomClient.js:1122 Consumer Success attached media audioType
RoomClient.js:1122 Consumer Success attached media videoType
RoomClient.js:581 Supported Constraints Object
RoomClient.js:596 Producer id 306b506c-8e30-4226-8ffe-a92aff4c2db4
Room.js:830 Room Client start audio
RoomClient.js:581 Supported Constraints Object
RoomClient.js:596 Producer id 4c99da33-d565-40a8-b145-d74d81d03911
RoomClient.js:1122 Producer Success attached media videoType
Room.js:851 Room Client start video
DevTools failed to load source map: Could not load content for https://unpkg.com/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://unpkg.com/@popperjs/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE



DOCKER LOGS: 
mirotalksfu    | [2021-12-10 11:20:17.260] [Server]
mirotalksfu    |
mirotalksfu    |        ███████╗██╗ ██████╗ ███╗   ██╗      ███████╗███████╗██████╗ ██╗   ██╗███████╗██████╗
mirotalksfu    |        ██╔════╝██║██╔════╝ ████╗  ██║      ██╔════╝██╔════╝██╔══██╗██║   ██║██╔════╝██╔══██╗
mirotalksfu    |        ███████╗██║██║  ███╗██╔██╗ ██║█████╗███████╗█████╗  ██████╔╝██║   ██║█████╗  ██████╔╝
mirotalksfu    |        ╚════██║██║██║   ██║██║╚██╗██║╚════╝╚════██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██╔══╝  ██╔══██╗
mirotalksfu    |        ███████║██║╚██████╔╝██║ ╚████║      ███████║███████╗██║  ██║ ╚████╔╝ ███████╗██║  ██║
mirotalksfu    |        ╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝      ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝ started...
mirotalksfu    |
mirotalksfu    |
mirotalksfu    | [2021-12-10 11:20:19.042] [Server] Listening on {
mirotalksfu    |   announced_ip: '180.211.96.18',
mirotalksfu    |   server: 'https://localhost:3010',
mirotalksfu    |   tunnel: 'https://337f-180-211-96-18.ngrok.io',
mirotalksfu    |   api_docs: 'https://localhost:3010/api/v1/docs',
mirotalksfu    |   mediasoup_version: '3.9.2'
mirotalksfu    | }
mirotalksfu    | [2021-12-10 11:21:32.585] [Server] Created room { room_id: '44494RareTiger' }
mirotalksfu    | [2021-12-10 11:21:32.597] [Server] User joined {
mirotalksfu    |   room_id: '44494RareTiger',
mirotalksfu    |   peer_info: {
mirotalksfu    |     detect_rtc_version: '1.4.1',
mirotalksfu    |     is_webrtc_supported: true,
mirotalksfu    |     is_mobile_device: false,
mirotalksfu    |     os_name: 'Windows',
mirotalksfu    |     os_version: '10',
mirotalksfu    |     browser_name: 'Chrome',
mirotalksfu    |     browser_version: 96,
mirotalksfu    |     peer_id: 'T9MgoGYHAtN3IhqUAAAB',
mirotalksfu    |     peer_name: 'a',
mirotalksfu    |     peer_audio: true,
mirotalksfu    |     peer_video: true,
mirotalksfu    |     peer_screen: false,
mirotalksfu    |     peer_hand: false
mirotalksfu    |   },
mirotalksfu    |   peer_geo: {
mirotalksfu    |     businessName: '',
mirotalksfu    |     businessWebsite: '',
mirotalksfu    |     city: 'Rancho Calaveras',
mirotalksfu    |     continent: 'North America',
mirotalksfu    |     country: 'United States',
mirotalksfu    |     countryCode: 'US',
mirotalksfu    |     ipName: '',
mirotalksfu    |     ipType: 'Residential',
mirotalksfu    |     isp: 'Hurricane Electric',
mirotalksfu    |     lat: '38.12742',
mirotalksfu    |     lon: '-120.85827',
mirotalksfu    |     message: 'Important: API Key required, please get your API Key at https://extreme-ip-lookup.com',
mirotalksfu    |     org: 'Hurricane Electric',
mirotalksfu    |     query: '65.49.68.17',
mirotalksfu    |     region: 'California',
mirotalksfu    |     status: 'success',
mirotalksfu    |     timezone: 'America/Los_Angeles',
mirotalksfu    |     utcOffset: '-08:00'
mirotalksfu    |   }
mirotalksfu    | }
mirotalksfu    | [2021-12-10 11:21:32.601] [Server] Refresh Participants count { room_id: '44494RareTiger', peer_counts: 1 }
mirotalksfu    | [2021-12-10 11:21:32.602] [Server] Get RouterRtpCapabilities { peer_name: 'a' }
mirotalksfu    | [2021-12-10 11:21:32.634] [Server] Create webrtc transport { peer_name: 'a' }
mirotalksfu    | [2021-12-10 11:21:32.651] [Room] Adding transport { transportId: 'fe8adefa-0668-46b2-9fe3-cfa0f9943fc4' }
mirotalksfu    | [2021-12-10 11:21:32.656] [Server] Create webrtc transport { peer_name: 'a' }
mirotalksfu    | [2021-12-10 11:21:32.657] [Room] Adding transport { transportId: '153bd0b6-a5b6-44da-8f5f-dc4b3d169a2f' }
mirotalksfu    | [2021-12-10 11:21:32.662] [Server] Get producers { peer_name: 'a' }
mirotalksfu    | [2021-12-10 11:21:32.740] [Server] Connect transport { peer_name: 'a' }
mirotalksfu    | [2021-12-10 11:21:32.757] [Server] Produce {
mirotalksfu    |   kind: 'audio',
mirotalksfu    |   peer_name: 'a',
mirotalksfu    |   producer_id: 'b81af9c5-d276-4f32-a83e-78d50df74151'
mirotalksfu    | }
mirotalksfu    | [2021-12-10 11:21:33.725] [Server] Produce {
mirotalksfu    |   kind: 'video',
mirotalksfu    |   peer_name: 'a',
mirotalksfu    |   producer_id: '6f9b6180-710d-4c5d-ab00-83c13573873a'
mirotalksfu    | }
mirotalksfu    | [2021-12-10 11:21:40.368] [Server] User joined {
mirotalksfu    |   room_id: '44494RareTiger',
mirotalksfu    |   peer_info: {
mirotalksfu    |     detect_rtc_version: '1.4.1',
mirotalksfu    |     is_webrtc_supported: true,
mirotalksfu    |     is_mobile_device: false,
mirotalksfu    |     os_name: 'Windows',
mirotalksfu    |     os_version: '10',
mirotalksfu    |     browser_name: 'Chrome',
mirotalksfu    |     browser_version: 96,
mirotalksfu    |     peer_id: 'oabWh4JYTapn5Y0TAAAD',
mirotalksfu    |     peer_name: 'adas',
mirotalksfu    |     peer_audio: true,
mirotalksfu    |     peer_video: true,
mirotalksfu    |     peer_screen: false,
mirotalksfu    |     peer_hand: false
mirotalksfu    |   },
mirotalksfu    |   peer_geo: {
mirotalksfu    |     businessName: '',
mirotalksfu    |     businessWebsite: '',
mirotalksfu    |     city: 'Rancho Calaveras',
mirotalksfu    |     continent: 'North America',
mirotalksfu    |     country: 'United States',
mirotalksfu    |     countryCode: 'US',
mirotalksfu    |     ipName: '',
mirotalksfu    |     ipType: 'Residential',
mirotalksfu    |     isp: 'Hurricane Electric',
mirotalksfu    |     lat: '38.12742',
mirotalksfu    |     lon: '-120.85827',
mirotalksfu    |     message: 'Important: API Key required, please get your API Key at https://extreme-ip-lookup.com',
mirotalksfu    |     org: 'Hurricane Electric',
mirotalksfu    |     query: '65.49.68.45',
mirotalksfu    |     region: 'California',
mirotalksfu    |     status: 'success',
mirotalksfu    |     timezone: 'America/Los_Angeles',
mirotalksfu    |     utcOffset: '-08:00'
mirotalksfu    |   }
mirotalksfu    | }
mirotalksfu    | [2021-12-10 11:21:40.381] [Server] Refresh Participants count { room_id: '44494RareTiger', peer_counts: 2 }
mirotalksfu    | [2021-12-10 11:21:40.427] [Server] Get RouterRtpCapabilities { peer_name: 'adas' }
mirotalksfu    | [2021-12-10 11:21:40.449] [Server] Create webrtc transport { peer_name: 'adas' }
mirotalksfu    | [2021-12-10 11:21:40.450] [Room] Adding transport { transportId: '0d432f62-1be6-412f-830e-0a10873ad507' }
mirotalksfu    | [2021-12-10 11:21:40.454] [Server] Create webrtc transport { peer_name: 'adas' }
mirotalksfu    | [2021-12-10 11:21:40.455] [Room] Adding transport { transportId: '4a1a6ffb-f227-4706-ab6c-f50dd440c6ce' }
mirotalksfu    | [2021-12-10 11:21:40.461] [Server] Get producers { peer_name: 'adas' }
mirotalksfu    | [2021-12-10 11:21:40.467] [Server] Consuming {
mirotalksfu    |   peer_name: 'adas',
mirotalksfu    |   producer_id: 'b81af9c5-d276-4f32-a83e-78d50df74151',
mirotalksfu    |   consumer_id: '6b037d56-f8e9-4904-ac17-65d6a1cc1628'
mirotalksfu    | }
mirotalksfu    | [2021-12-10 11:21:40.474] [Server] Consuming {
mirotalksfu    |   peer_name: 'adas',
mirotalksfu    |   producer_id: '6f9b6180-710d-4c5d-ab00-83c13573873a',
mirotalksfu    |   consumer_id: 'c505ab74-1ed2-48cd-96f1-e039d5967b8b'
mirotalksfu    | }
mirotalksfu    | [2021-12-10 11:21:40.477] [Server] Connect transport { peer_name: 'adas' }
mirotalksfu    | [2021-12-10 11:21:40.545] [Server] Connect transport { peer_name: 'adas' }
mirotalksfu    | [2021-12-10 11:21:40.557] [Server] Produce {
mirotalksfu    |   kind: 'audio',
mirotalksfu    |   peer_name: 'adas',
mirotalksfu    |   producer_id: '306b506c-8e30-4226-8ffe-a92aff4c2db4'
mirotalksfu    | }
mirotalksfu    | [2021-12-10 11:21:40.561] [Server] Consuming {
mirotalksfu    |   peer_name: 'a',
mirotalksfu    |   producer_id: '306b506c-8e30-4226-8ffe-a92aff4c2db4',
mirotalksfu    |   consumer_id: '95eeb159-5293-4e21-a2bc-4536cfb8584e'
mirotalksfu    | }
mirotalksfu    | [2021-12-10 11:21:40.570] [Server] Connect transport { peer_name: 'a' }
mirotalksfu    | [2021-12-10 11:21:40.674] [Server] Produce {
mirotalksfu    |   kind: 'video',
mirotalksfu    |   peer_name: 'adas',
mirotalksfu    |   producer_id: '4c99da33-d565-40a8-b145-d74d81d03911'
mirotalksfu    | }
mirotalksfu    | [2021-12-10 11:21:40.685] [Server] Consuming {
mirotalksfu    |   peer_name: 'a',
mirotalksfu    |   producer_id: '4c99da33-d565-40a8-b145-d74d81d03911',
mirotalksfu    |   consumer_id: 'ae4a8657-1f77-4b5b-a94a-2344e20beac9'
mirotalksfu    | }

**Comment by JagdishTech** [comment]
Also tried with NGROCK tunnel - still same error

![image](https://user-images.githubusercontent.com/89624981/145567528-949c44e4-4d11-4320-95d5-c1318c56a6c0.png)

**Comment by miroslavpejic85** [comment]
Hello @JagdishTech, Thanks for trying MiroTalk :)
The problem seems you're missing the port-forwarding part, look at this: https://github.com/miroslavpejic85/mirotalksfu/issues/26#issuecomment-986309051 Let me know if persist? Regards

**Comment by JagdishTech** [comment]
@miroslavpejic85 thanks for your reply,
Let me retry and get back to you.

**Comment by miroslavpejic85** [comment]
Hello @subzero355,
You don't need the Ngrok in your case, The announced IP should be your public static IP.

**Comment by subzero355** [comment]
Thanks @miroslavpejic85 , that worked like charm behind a docker and SWAG
