### ISSUE TITLE
Exploring the Feasibility of Simultaneously Viewing Multiple Screens in a Proctoring System

### ISSUE THREAD

**Issue by gsabarinath02** [miroslavpejic85/mirotalksfu#100]
Hello,

I am currently in the process of developing a proctoring system, and I am interested in the possibility of displaying multiple persons' screens simultaneously. Specifically, I would like to be able to view the screens of several individuals simultaneously, similar to the functionality offered by Discord, such that upon entering a room, I am able to view all streams simultaneously on my system.

I am wondering if it is technically feasible to achieve this and if there are any applications available on GitHub that could serve as a reference for the implementation of such functionality. Any insights or recommendations would be greatly appreciated.

Thank you in advance.

**Comment by miroslavpejic85** [comment]
Hello @gsabarinath02,

You can use Direct Join Room, but the screen sharing permissions is a mandatory to be approved by the users device respecting the privacy of the user! Other than that, you should be able to see all shared screens without problems in the room.

I'm going to close here, as you proposed the same question about on [Discord](https://discord.gg/rgGYfeYW3N) in all possible channels :)
