### ISSUE TITLE
Keep the client alive when running background on ios

### ISSUE THREAD

**Issue by qiangweihewu** [miroslavpejic85/mirotalksfu#101]
### Feature request

Keep the client alive when running background on ios even when the phone/ipad screen is locked. 

By keeping the client alive, I mean:
1. You are kept connectedd to the room you joined
2. You can hear the speaker even though you are muted.
3. You can come back to the client and open the camera any time you want as long as the meeting is going on

### Pros

1. You don't need to keep the web client in the front all the time during the meeting 
2. Some meetings you just need to listen, no need to show up on camera
3. Sometimes you have to switch to the other apps to deal with something.

### Additional context
Possible way?
I found it can be kept alive when running background if the user keep the audio button on. So I came up this idea that
whether the user turns on or turns off the microphone button in the client, keep the requirement of accessing to the microphone on iOS system. When the user turns off the microphone button,  instead of telling the iOS system there's no need of microphone, just keep the occupation, while stop transmitting any audio information to the server and other attendees. 

Do you think it possible? 

Thanks!

**Comment by miroslavpejic85** [comment]
Hello @qiangweihewu,

> Keep the client alive when running background on ios even when the phone/ipad screen is locked.

I tested it right now on my iPhone, and when I lock the screen I can hear the participants as well.

![mirotalk-sfu-iphone-look-screen](https://user-images.githubusercontent.com/70838434/232214875-e3483460-42c3-4ac8-a13b-22a14109ae2a.jpg)

MiroTalk being a [progressive web app](https://www.youtube.com/watch?v=Z8MjdQGyjfA) (lives in the browser), as long as you keep the browser tab open, you will be able to do all points mentioned in the Pros, if not, is like end the client connection at all with the room.

Please join with us on [forum](https://discord.gg/rgGYfeYW3N) too, where we can discuss also all together in the `ideas-and-suggestions` channel.

Thank you!
