### ISSUE TITLE
i am getting Producer/Consumer Transport Failed

### ISSUE THREAD

**Issue by TalhaSoftPlace** [miroslavpejic85/mirotalksfu#103]
i am getting Producer Transport Failed and consumer Transport Failed when i open my video or mic then this issue arise if my video and audio remains turn off then i don't get Producer Transport or consumer Transport issue. is this a bug or issue on my side? and how do i resolve it?

## Discord chat

Join with us on Discord and ask questions, create discussion, leave feedback.

- https://discord.gg/rgGYfeYW3N

**Comment by miroslavpejic85** [comment]
Hello @TalhaSoftPlace,
Please use short title :) You can describe it later...

For questions join with us on 👉 [discord](https://discord.gg/rgGYfeYW3N) -> channel `help & support`

> i am getting Producer Transport Failed and consumer Transport Failed when i open my video or mic then this issue arise if my video and audio remains turn off then i don't get Producer Transport or consumer Transport issue. is this a bug or issue on my side? and how do i resolve it?

If you not have this issue on the official demo: https://sfu.mirotalk.com It's definitely some of your side misconfiguration.
You can follow 👉 [this documentation](https://github.com/miroslavpejic85/mirotalksfu/blob/main/docs/self-hosting.md) on how to self-host it correctly.
Thank you for the understanding.
