### ISSUE TITLE
Mic issue on mobile

### ISSUE THREAD

**Issue by TalhaSoftPlace** [miroslavpejic85/mirotalksfu#106]
### Mic Issue Bug

while meeting when I turn off the mic I can't hear voice for a moment. I mean when we turn off the mic speaker also got effected for a moment and we can't hear the attendees voice as well.

### To Reproduce

1. Go to Mobile create or join meeting.
2. Ask the other person to start talking continuously.
3. When he/she start taking turn your mic off you will not hear his/her voice for a moment.
### Expected behavior

Mic shouldn't effect the speaker as we can see on google meet. when we turn the mic off we can still hear voice.

### Mobile

Please complete the following information:

 - Device or OS: [e.g. iPhone, Android]
 - Browser [e.g. Chrome, Safari]

**Comment by miroslavpejic85** [comment]
hello @TalhaSoftPlace,
Maybe it was fixed in [this commit](https://github.com/miroslavpejic85/mirotalksfu/commit/5186705cef9fc06659ae4774881fa89bd50b17c3). Thank you.

**Comment by miroslavpejic85** [comment]
> When he/she start taking turn your mic off you will not hear his/her voice for a moment. 

I Tested, for me seems ok now, maybe if it's happen again `for a moment` i not see it as a high priority issue. 
Join also with us on [discord forum](https://discord.gg/rgGYfeYW3N) where we can also discuss all toghether, in case happen again. 

Thank you and have a good weekend.
