### ISSUE TITLE
when connection lost wait 60sec before closing connection

### ISSUE THREAD

**Issue by seemab40615** [miroslavpejic85/mirotalksfu#107]
Hi can you add a feature like when internet gets disconnected it should wait for 1minute and saying message that "retrying to connect..." and if internet gets resolved in 60 second then it should continue else it should close the producer or consumer.

**Comment by miroslavpejic85** [comment]
If the server is away for some reason (updates and so on), i currently close all the producer and consumer transports on the client side as they are lost on server restart and redirect it to to http://sfu.mirotalk.com/newroom

What I can do, is to not  redirect the client, but remain in the current room, trying to reconnect to the server until the server goes up,  when the connection is established again, I will reload the page to rejoin again in the room. 

In this way, you will not lose the connection and you will be in the same room as before.

**Comment by miroslavpejic85** [comment]
Done, the client will be reconnected to the same room, when the server come back up.

<img width="873" alt="client-wait-to-reconnect" src="https://github.com/miroslavpejic85/mirotalksfu/assets/70838434/a32404ec-a0d7-42bc-aab1-d604d8a30754">
