### ISSUE TITLE
MiroTalkSFU behind nGinx proxy?

### ISSUE THREAD

**Issue by Kareszrk** [miroslavpejic85/mirotalksfu#108]
I would like to ask a question whether mirotalksfu works behind proxy or not.
If it works, what does it require to do so?

Right now since I putted mirotalksfu behind proxy I never get into a room. It asks for permissions to camera and microphone, then for my name. But it never joins to the room, however if I open the website with the IP address, everything works.

**Comment by miroslavpejic85** [comment]
For the questions use the [forum](https://discord.gg/rgGYfeYW3N). Thank you.
