### ISSUE TITLE
hosted deployment mirotalk, but no audio sound can be heard when opening the meeting

### ISSUE THREAD

**Issue by meichaofan** [miroslavpejic85/mirotalksfu#109]
hi team:
     first of all, thank you very much for making such a great project. when i deployed the project on my own server, I found a problem. when entering the meeting, I couldn't turn on the audio sound. can you help me check what the problem ?  thank you. our website is https://room.libaspace.com

**Comment by miroslavpejic85** [comment]
hello @meichaofan,

GitHub is for bugs/req, please ask questions on the [forum](https://discord.gg/rgGYfeYW3N). You can find there a lot of answers regarding.

As specified in the [docs/self-hosting](https://github.com/miroslavpejic85/mirotalksfu/blob/main/docs/self-hosting.md)

1. Make sure you put correctly as `announcedIp` your Server public IPV4 in `app/src/config.js`

```js
{
	ip: '0.0.0.0',
	announcedIp: '47.88.7.136',
}
```  

2. Make sure your `firewall` not block the `RTCPorts RANGE 40000-40100 (UDP/TCP)`

If firewall enabled, Set the `inbound rules` as the following:

| Port range  | Protocol | Source    | Description         |
| ----------- | -------- | --------- | ------------------- |
| 3010        | TCP      | 0.0.0.0/0 | App listen on tcp   |
| 40000-40100 | TCP      | 0.0.0.0/0 | RTC port ranges tcp |
| 40000-40100 | UDP      | 0.0.0.0/0 | RTC port ranges udp |

BR. Miroslav
