### ISSUE TITLE
Docker - No Stun Servers Specified

### ISSUE THREAD

**Issue by srinimit** [miroslavpejic85/mirotalksfu#11]
I tried docker running this application on my local machine with the given steps.

The video input starts and stopped immediately.

below were the console logs:
```
WebRTC: ICE failed, add a STUN server and see about:webrtc for more details
Producer Transport failed RoomClient.js:272:37
Producer transport close RoomClient.js:508:25
```

**Comment by Jaideep25** [comment]
Hello @srinimit !
Could you please specify your system OS version? Thanks!

**Comment by srinimit** [comment]
Hi,
Mac Big Sur 11.6
Browser: Firefox 92.0.1

**Comment by miroslavpejic85** [comment]
Hello @srinimit,

On config.js change this and then rebuild the image:

```js
announcedIp: YOUR-PUBLIC-IP-HERE, // replace by public static IP address https://api.ipify.org
```

Then port-forwarding something like this on `router` settings:

|  Name         |  Protocol  | Port Wan    | Port Lan    |  IP Destination   | 
|---------------|------------|-------------|-------------|-------------------|
| `MiroTalkSfu`   | `TCP/UDP`  | 40000:40100 | 40000:40100 | `Your Local IP`   |
| `MiroTalkSfu `   | `TCP/UDP`  | 3010        | 3010        | `Your Local IP`   |

Make sure your firewall not blocking rtcPorts range : `40000:40100`

Regards
