### ISSUE TITLE
Can I use the mirotalksfu on the premise scenario ? 

### ISSUE THREAD

**Issue by leviethung2103** [miroslavpejic85/mirotalksfu#110]
## Discord chat

Join with us on Discord and ask questions, create discussion, leave feedback.

- https://discord.gg/rgGYfeYW3N

Hello, 
I would like to ask whether can I use the mirotalksfu on the premise scenario ? 

I want to develop a video call application for my company. Due to the privacy issue, I want to find the another solution to do that ?

**Comment by miroslavpejic85** [comment]
For questions use the forum. 
Thank you.
