### ISSUE TITLE
Change default settings

### ISSUE THREAD

**Issue by rogerdz** [miroslavpejic85/mirotalksfu#112]
How can I set the setting value automatically every time I create a room ?
![image](https://github.com/miroslavpejic85/mirotalksfu/assets/78783748/68c87ac1-c14a-4e76-a15c-e1e9f6366ae1)

**Comment by miroslavpejic85** [comment]
When a user joins a room, the settings will be loaded from the local storage exactly as they were before the user left the room. Any changes made to the settings during the user's previous session will be preserved and applied upon rejoining the room.

**Comment by rogerdz** [comment]
Hi @miroslavpejic85 
Thank for your response, you are so fast.
Can we set default setting value in app/src/config.js, it makes it more convenient ?

**Comment by miroslavpejic85** [comment]
I would prefer the user to choose the theme, position of the buttons, and other preferences based on their liking.
