### ISSUE TITLE
Support for Arm-based Docker images

### ISSUE THREAD

**Issue by rogerdz** [miroslavpejic85/mirotalksfu#113]
Hi,
I found out that only amd64 docker image can be found on dockerhub.
I wonder if there is some plan or try about native support on arm architecture ?

**Comment by rogerdz** [comment]
You can use github workflow with docker/build-push-action for build docker image multi arch 
Example: https://github.com/axllent/mailpit/blob/develop/.github/workflows/build-docker.yml

**Comment by miroslavpejic85** [comment]
Hey @rogerdz!

Thank you so much for this PR! 

Correct me if I understood correctly. 

1. I have to create an Environment on GitHub es `docker-hub`, then add the two variables in `secrets` which are needed to connect to my docker-hub. 

<img width="1138" alt="mirotalk-docker-hub" src="https://github.com/miroslavpejic85/mirotalksfu/assets/70838434/02f86d2f-0ebc-4bd4-afa1-092e8bfccb16">

2. Every time someone push changes to the repository, the GitHub Actions workflow will be triggered, and the Docker image will be built and pushed to Docker Hub for both platforms (`linux/amd64, linux/arm64`).


The result is that the image will be only one as before `mirotalksfu/latest` but will also support linux/arm64?

And have you had a chance to test this GitHub Actions workflow?

Thank you!
