### ISSUE TITLE
CORS error 

### ISSUE THREAD

**Issue by rogerdz** [miroslavpejic85/mirotalksfu#114]
I get error CORS when run app:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://translate.googleapis.com/element/log?format=json&hasfast=true&authuser=0. (Reason: CORS request did not succeed). Status code: (null).
![image](https://github.com/miroslavpejic85/mirotalksfu/assets/78783748/ab7ad35f-9b93-400e-838e-e8bd315a3564)

**Comment by miroslavpejic85** [comment]
Do you use any browser extensions?

Browser extensions can indeed block requests and interfere with the behavior of websites, including causing issues with CORS (Cross-Origin Resource Sharing). Some browser extensions, such as ad blockers, privacy-enhancing extensions, or security extensions, may have features that block certain requests to external domains or modify the behavior of web pages.

Here are a few scenarios where browser extensions can cause CORS-related issues:

1. **Ad Blockers**: Ad blockers are known to block requests to ad servers or tracking domains. Some ad blockers might also have additional features that block requests to certain domains altogether, including legitimate API endpoints, which can lead to CORS-related problems.

2. **Privacy and Security Extensions**: Extensions designed to enhance privacy or improve security may block requests to external domains to prevent tracking or protect against potential security risks. In some cases, these extensions might block necessary API requests unintentionally.

3. **Firewalls and Security Software**: Some security software, such as firewall applications or antivirus suites, can also have web filtering capabilities that block specific domains or requests for security reasons.

4. **Request Modification Extensions**: Certain extensions are explicitly designed to modify or manipulate requests made by the web page. These extensions can interfere with CORS headers or modify the request in a way that triggers CORS-related errors.

To identify whether a browser extension is causing the issue, you can try the following steps:

1. **Disable Browser Extensions**: Temporarily disable all browser extensions, and then try accessing the web page or making the request again. If the CORS-related problem disappears, it's likely that one of the extensions was causing the issue.

2. **Whitelist Specific Extensions**: If you identify a particular extension causing the problem, check its settings to see if it has any features related to web request blocking, domain blocking, or CORS. Some extensions allow you to whitelist specific domains to prevent blocking.

3. **Try a Different Browser**: Test the web page or request in a different browser where you haven't installed any extensions. If the CORS issue disappears, it strongly suggests that an extension in your original browser is causing the problem.

4. **Check the Browser Developer Console**: When the CORS error occurs, check the browser's developer console (usually accessed by pressing F12 or right-clicking and selecting "Inspect") for any relevant error messages. It might provide additional information about the cause of the CORS block.

If you find that a browser extension is indeed causing the CORS issue, you can consider adding exceptions or whitelisting the necessary domains in the extension settings to allow the desired requests. Additionally, educating users about potential conflicts with certain browser extensions and suggesting temporary disabling of those extensions can be helpful.

Please for discussions, help & support join us on [discord](https://discord.gg/rgGYfeYW3N) 
Thank you.
