### ISSUE TITLE
UI Enhancements similar to Mirotalk

### ISSUE THREAD

**Issue by srinimit** [miroslavpejic85/mirotalksfu#12]
I would like to request some UI enhancements similar to Mirotalk

1) If the video is turned off, it would be great if we could still show the grid with the name on the screen .
![image](https://user-images.githubusercontent.com/20786790/134818354-9d6a2efb-b3fe-430e-a0be-eaea14215a48.png)

Love this app. This app is gonna be the next great thing !

**Comment by miroslavpejic85** [comment]
- Note: Add also participant's audio status...

**Comment by srinimit** [comment]
It would be great to see if the user is on mute. Plus when video is off, it would look nice if we have a wave like animation around the name whenever the user speaks, just to indicate that the user is speaking.

**Comment by miroslavpejic85** [comment]
Done [here](https://github.com/miroslavpejic85/mirotalksfu/commit/d1674ed382e25c93308f8bc8effe590ffbcdb700)
- Desktop view on participants video off + audio status...

<img width="1483" alt="mirotalksfu-video-off" src="https://user-images.githubusercontent.com/70838434/135657204-cf73ba20-8d36-4340-a3f7-0cbdf4a05e81.png">

<img width="1680" alt="mirotalksfu-peers" src="https://user-images.githubusercontent.com/70838434/135657220-f900c77c-5098-4a25-b157-82125e1f68d0.png">

- Mobile compatible, view small size `320x480`

<img width="320" alt="mirotalksfu-mobile" src="https://user-images.githubusercontent.com/70838434/135657241-6e1e0fac-c395-4078-9e53-aa3ecf79e529.png">

**Comment by srinimit** [comment]
Looks Awesome !
