### ISSUE TITLE
How to scale ?

### ISSUE THREAD

**Issue by eznix86** [miroslavpejic85/mirotalksfu#121]
It would be interesting to know how to scale this using docker swarm or something like that and how to configure it inside the README

## Discord chat

Join with us on Discord and ask questions, create discussion, leave feedback.

- https://discord.gg/rgGYfeYW3N

**Comment by miroslavpejic85** [comment]
Please for questions use the [official forum](https://discord.gg/rgGYfeYW3N). Thank you!
