### ISSUE TITLE
Push to talk

### ISSUE THREAD

**Issue by AlexAT** [miroslavpejic85/mirotalksfu#122]
Please add push to talk function ( https://github.com/miroslavpejic85/mirotalk/issues/143 ) to SFU client as well.
Kind thanks.

**Comment by miroslavpejic85** [comment]
![mirotalk-sfu-push-to-talk](https://github.com/miroslavpejic85/mirotalksfu/assets/70838434/f1a9f456-6dbd-4316-a255-09c74146613a)

**Comment by AlexAT** [comment]
Wow, you're the best, thanks!
