### ISSUE TITLE
"Keep room name through authentication" feature only works for some URL formats

### ISSUE THREAD

**Issue by rawtaz** [miroslavpejic85/mirotalksfu#125]
### Describe the bug

I'm afraid the [newly added](https://github.com/miroslavpejic85/mirotalksfu/commit/6b08df99bc9e533e6062e4f4951e618452865233) feature suggested in #124 isn't working entirely, at least from what I can tell:

- If I go to `http://mydomain.com/join/test` or `http://mydomain.com/join?room=test` I get the authentication page, enter valid credentials, and is then redirected to `http://mydomain.com/logged?room=` (yes, the room name is missing), so I still have to enter the room name manually.
- If I go to `http://mydomain.com/?room=test` it works - I get the authentication page, enter valid credentials, and is then redirected to `http://mydomain.com/logged?room=test`, so that I don't have to enter the room name manually.

### To Reproduce

1. Go to `http://mydomain.com/join/test` or `http://mydomain.com/join?room=test` in a MiroTalk SFU instance that is protected by a username and password.
1. Enter a valid username and password to authenticate.
1. Notice that instead of being redirected to `http://mydomain.com/logged?room=test` (not having to enter a room name) you end up on `http://mydomain.com/join?room=` (having to enter a room name).

### Expected behavior

Accessing the instance using either of `http://mydomain.com/join/test`, `http://mydomain.com/join?room=test` and `http://mydomain.com/?room=test` should let you not have to enter the room name after authentication (since the room name is already supplied in the URL).

### Screenshots

N/A

### Desktop - Mobile

Please complete the following information:

 - Device or OS: macOS
 - Browser: Chrome, Safari
 - Version: Latest

### Additional context

The reason I expect not only the `http://mydomain.com/?room=test` URL format to work but also `http://mydomain.com/join/test` and `http://mydomain.com/join?room=test` is that the last one of these is described as supported under "Direct join" in the [README.md](https://github.com/miroslavpejic85/mirotalksfu/blob/main/README.md) and the second-to-last is the one you get as the link to share with others once you joined a room. So I don't see why these would not support the feature at hand as well.

**Comment by miroslavpejic85** [comment]
Hi @rawtaz, I should have fixed it.

When [host protection is enabled](https://github.com/miroslavpejic85/mirotalksfu/commit/ab21686e9ad4b75e14c3ee020141d61b33111dde#commitcomment-62398736), the URL format for direct room access after authentication should be as follows:

- `https://mydomain.com/?room=test`

After host authentication, participants can join the room using any of the following URL formats:

- `https://mydomain.com/join/test`
- `https://mydomain.com/join/?room=test`
- `https://mydomain.com/join/?room=test&password=0&name=mirotalksfu&audio=1&video=1&screen=0&notify=0`

**Comment by rawtaz** [comment]
Hi,

Thanks for the explanation. I have some feedback on that though:

- What is the point of having two of the URL formats work only after the visitor is already authenticated?
- It's not great UX in the following way:
  - Imagine you (as the inviter of an ad-hoc meeting) go to your instance, log in, enter a room name and your own name.
  - Then when entering the room you get the Sharing dialog, in which you can very easily copy the link to the meeting.
  - This list has the format `https://mydomain.com/join/test`, not the `https://mydomain.com/?room=test` one.
  - Naturally, you want to just click the button to copy `https://mydomain.com/join/test` and share that with your expected participants.
  - This doesn't currently work though, because when they use that link, they will still end up at the "enter room name" page after authenticating.
  - The alternative you have to fix that is to edit/hand-craft the URL to be the `https://mydomain.com/?room=test` format, which takes away the point of things (in this case it's easier to instead just tell participants to log in and then enter the room name themselves).

Is it complicated to make all three URL formats work with the "Keep room name through authentication" feature?

**Comment by miroslavpejic85** [comment]
The inclusion of two URL formats, one with a simple path and another with query parameters, serves the purpose of offering flexibility to accommodate various usage scenarios. Let me elaborate:

1. `https://mydomain.com/join/test`: This format allows users to join the 'test' room while providing them with the option to configure their camera, audio, screen settings, and name before entering the room.

2. `https://mydomain.com/join/?room=test&password=0&name=mirotalksfu&audio=0&video=0&screen=0&notify=0`: This format enables users to directly join the 'test' room by specifying their preferences through query parameters. For instance:
   - `https://mydomain.com/join/?room=test&name=userNam1`
   - `https://mydomain.com/join/?room=test&name=userName2&video=0&audio=0`
   - `https://mydomain.com/join/?room=test&name=userName3&video=0&audio=1`
   - `https://mydomain.com/join/?room=test&name=userName4&video=1&audio=0`   
   - `https://mydomain.com/join/?room=test&name=userName5&video=1&audio=1`   
   - ....

   You can mix and match these query parameters as needed.

With this approach, users can seamlessly access the desired room using both the simplified URL path (e.g., https://mydomain.com/join/test) and the URL with query parameters, providing greater convenience and adaptability.
