### ISSUE TITLE
 Request: authentication option to create a new room

### ISSUE THREAD

**Issue by ioscanner** [miroslavpejic85/mirotalksfu#13]
Feature request: Ability to prevent creation of a new room unless authenticated.

**Comment by miroslavpejic85** [comment]
The Ethics of MiroTalk is to not have any form of login - plug-in - download and so on ... 

Just a click on the link and join in the room...

Eventually you can use the API already implemented to get a dedicated room.

Or for custom uses, you can adapt the code ... ;)

Regards
