### ISSUE TITLE
Allow access to share video and audio by moderator

### ISSUE THREAD

**Issue by sarabisohrab** [miroslavpejic85/mirotalksfu#137]
Hi
If I set moderator option as I set in the attached image, can moderator allow someone to share his video and audio later in that session?

![image](https://github.com/miroslavpejic85/mirotalksfu/assets/26074239/e976041d-e50f-4315-b4ba-69bca5311e84)

## Discord chat

Join with us on Discord and ask questions, create discussion, leave feedback.

- https://discord.gg/rgGYfeYW3N

**Comment by miroslavpejic85** [comment]
# Enable participant video/audio/screen

Hello @sarabisohrab, 

All moderator commands are dynamically updated in real-time within the room. As a presenter, you now have the capability to enable or disable audio, video, and screen sharing for specific participants directly from the participants list in the chat. 

To uphold privacy, participants will need to confirm the action, ensuring a secure and consent-driven environment. This real-time control enhances the moderation experience, allowing seamless adjustments during live interactions. 

## Enable Camera

![mirotalk-sfu-unhide-participant](https://github.com/miroslavpejic85/mirotalksfu/assets/70838434/9c146d33-3122-44d0-9e12-017f902bb9c5)

![mirotalk-sfu-unhide-participant-popup](https://github.com/miroslavpejic85/mirotalksfu/assets/70838434/f44bf52b-9e6a-4109-a626-6b69548d8ab2)

## Enable Microphone

![mirotalk-sfu-unmute-participant](https://github.com/miroslavpejic85/mirotalksfu/assets/70838434/3165999b-5cbb-4c21-b283-086001e5be5c)

![mirotalk-sfu-unmute-participant-popup](https://github.com/miroslavpejic85/mirotalksfu/assets/70838434/1e36d092-124c-404d-8a15-bcfea752af8c)

## Start screen share

![mirotalk-sfu-start-screen-participant](https://github.com/miroslavpejic85/mirotalksfu/assets/70838434/64ac76b8-3e86-4bd1-afa2-4711c1e7908e)

![mirotalk-sfu-start-screen-participant-popup](https://github.com/miroslavpejic85/mirotalksfu/assets/70838434/3e55c0f6-be4b-47e1-99ae-2291ac5f2236)

## Forum

For any additional questions, ideas, and suggestions, please join us on the [official forum](https://discord.gg/rgGYfeYW3N). 

Thank you, and enjoy your MiroTalk SFU video conferences!
