### ISSUE TITLE
SFU implementation vs mesh Mirotalk 

### ISSUE THREAD

**Issue by pragmatech** [miroslavpejic85/mirotalksfu#14]
Hi. As ever, thanks for sharing your impressive work. I hope you take a breather sometime too heh. 
In addition to your different hosting environments for the two (Railway won't suffice for mediasoup SFU?), I'm curious as to your experience with tangible differences in the two implementations. Specifically, if one has aspirations for clubhouse like audio-centric use, might that sans-video approach work upon the mesh version? Other comparisons, based on your experience would also be interesting to learn. Thanks!

**Comment by miroslavpejic85** [comment]
`MiroTalk P2P`: https://github.com/miroslavpejic85/mirotalk

Architecture: `WebRTC Mesh` (peer to peer between browsers)

![image](https://user-images.githubusercontent.com/70838434/135707736-f2ea1bf0-30cb-414d-bba3-d12e02571f48.png)

`Unlimited rooms, no limit of time`, supports `5 users in the single room` To have a good video-audio quality. The quality of the call is inversely proportional to the number of people on the call.

Required: `Client PC` (peers) must have a `good Bandwith and CPU`.

Deploy: Any host that support `Node.js` like: [railway](https://railway.app/) or [heroku](https://www.heroku.com/) (Free service) or [DigitalOcean](https://m.do.co/c/1070207afbb1) for personal vm server (for a fee) ...

Bonus: There are an option to use it directly from your `LOCAL PC` and thanks to [Ngrok](https://ngrok.com/) you will be able to have conference and will be reached outside your local network, no matter where you are! 

<br/>

`MiroTalk SFU` (This one): https://github.com/miroslavpejic85/mirotalksfu

Architecture: `WebRTC SFU` (Server with Selective Forwarding Unit) using [mediasoup](https://mediasoup.org/)

![image](https://user-images.githubusercontent.com/70838434/135707831-e1e5b7ab-d9b7-48c8-b70e-b9c33cc56a24.png)

`Unlimited rooms, no limit of time`, and in theory `no limit of users`. Routing is a multiparty topology, where each participant sends its media to this integrated server, and receives all other's media from it.

Required: `Server` must have a `very good Bandwidth`, and good RAM and CPU.

Deploy: `VM` that support `Node.js and other stuff` like: [DigitalOcean](https://m.do.co/c/1070207afbb1) or [amazon-aws](https://aws.amazon.com/it/) (paid service) ...

Bonus: There are an Option to use it directly from your `LOCAL PC` by some extra settings and thanks to [Ngrok](https://ngrok.com/) you will be able to have conference and will be reached outside your local network, no matter where you are!

Based on the amount of users you have, you can choose the right solution for you :)

I hope I have clarified your doubts about the difference of the two versions? 

Thanks and have a nice day.

Regards

**Comment by nitad54448** [comment]
Hi
I installed the SFU version on my LTS 20.04 selfhosted. It seems to work locally but not from outside. I did not get certificates but I use a caddy reverse proxy, which I configured correctly. I get a certificate error.  Is there a way to use caddy's SSL certificates ?
Thanks

**Comment by miroslavpejic85** [comment]
Hello @nitad54448, 
What do you mean by  `I get a certificate error` ? 
If you using the MiroTalk SSL default certificates on: https://github.com/miroslavpejic85/mirotalksfu/tree/main/app/ssl
At most the browser could tell you that it is an unknown certificate, you accept it and you can use Mirotalk in HTTPS.
I haven't tried caddy, I usually use Let's Encrypt for trusted certificates.
Regards

**Comment by VladimirGorin** [comment]
Good afternoon Miroslav, I have a question, how can I place your application on hosting, not in the way that you indicated in the documentation, but with the standard npm run build command, but the problem is when I run it, I get an error, how can I run the npm run build comm
![New Bitmap Image](https://user-images.githubusercontent.com/99133904/179698917-44e19ae2-f0d8-4064-aaa1-546cf2859fda.jpg)
and here is an example what a normally compiled file looks like

**Comment by miroslavpejic85** [comment]
Hello @VladimirGorin,
For questions please do not post here but join with us on [Discord forum](https://discord.gg/rgGYfeYW3N) - `hepl-and-support channel`. Thank you!

**Comment by umair-me** [comment]
Good to have this in wiki.

**Comment by miroslavpejic85** [comment]
> Good to have this in wiki.

https://docs.mirotalk.com/html/overview.html
