### ISSUE TITLE
Can we give host to other participants ,because when i am using it if host got disconnected when we can able to record nor the host didn,t go to other user

### ISSUE THREAD

**Issue by prabii** [miroslavpejic85/mirotalksfu#140]
# MiroTalk forum

If you have `ideas, suggestions, questions, doubts` about MiroTalk or `need support`, please use the MiroTalk Forum instead:

👉 [https://discord.gg/rgGYfeYW3N](https://discord.gg/rgGYfeYW3N)

**Comment by miroslavpejic85** [comment]
The answer is Yes, but as specified use the forum please not open issue here. Thank you!
