### ISSUE TITLE
Docker on AMD64: [Server] Create Worker ERR

### ISSUE THREAD

**Issue by ccclever2** [miroslavpejic85/mirotalksfu#144]
# Bug Report

## Describe the bug

Mediasoup worker error when self-hosting mirotalk-sfu using self-hosted guide

Error log:

```
mirotalksfu  | [2024-02-16 12:47:37.071] [Server] Create Worker ERR ---> Error: [pid:27, code:40, signal:null]
mirotalksfu  |     at ChildProcess.<anonymous> (/src/node_modules/mediasoup/node/lib/Worker.js:144:43)
mirotalksfu  |     at ChildProcess.emit (node:events:517:28)
mirotalksfu  |     at ChildProcess.emit (node:domain:489:12)
mirotalksfu  |     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
```

## To reproduce

1. Clone mirotalk-sfu repo
2. copy docker-compose and config file
3. docker compose up
4. Container exits with error

## Expected behavior

Container should not exit

## Desktop 

 - Device or OS: Debian12, AMD64

## Additional context

I successfully deployed the same image on my M1 Mac on ARM64

**Comment by miroslavpejic85** [comment]
Hello @ccclever2,

The error message indicates that there was a problem creating a worker process, and it provides some details about the error.

The error code `40` typically indicates a failure in the child process, but without more context or the full error message, it's challenging to pinpoint the exact cause of the issue. However, here are a few steps you can take to troubleshoot this problem:

1. **Check Logs**: Look for additional log messages or error details that might provide more information about what went wrong. Sometimes, there might be more specific error messages that can help diagnose the issue.

2. **Review Configuration**: Ensure that your MirotalkSFU server is correctly configured with the necessary settings and dependencies. Make sure all required configurations are in place and correctly set up.

3. **Check System Resources**: Verify that your system has enough resources (CPU, memory, disk space) available to create new worker processes. Insufficient resources can sometimes cause worker creation failures.

4. **Update Dependencies**: Ensure that all dependencies for MirotalkSFU are up-to-date. Outdated dependencies or incompatible versions could lead to errors.

5. **Seek Community Support**: If you're unable to troubleshoot the issue independently, it's advisable to seek assistance from the Mirotalk community. You can connect with fellow users and experts through the [help & support channel](https://discord.gg/rgGYfeYW3N) on Discord. Additionally, exploring discussions on the [mediasoup forum](https://mediasoup.discourse.group) might provide valuable insights or solutions related to your concern. Community forums and channels often offer collective knowledge and experiences that can help resolve technical issues effectively.

Thank you!
