### ISSUE TITLE
The chat will automatically crash after some time.

### ISSUE THREAD

**Issue by ramdassaykar7** [miroslavpejic85/mirotalksfu#146]
# Bug Report

`IMPORTANT`: We primarily use GitHub as an issue tracker. Just open an issue here if you have encountered a bug in MiroTalk.
If you have `ideas, suggestions, questions, doubts` about MiroTalk or `need support`, please use the MiroTalk Forum instead:

👉 [https://discord.gg/rgGYfeYW3N](https://discord.gg/rgGYfeYW3N)

## Desktop - Mobile

Please complete the following information:

 - Device or OS: [e.g. iPhone6, Android, Linux, Mac, Windows]
 - Browser [e.g. Chrome, Safari]

**Comment by miroslavpejic85** [comment]
We kindly request that you ensure all sections of the `bug template are completed` prior to submission, as insufficient data may hinder our ability to understand the underlying cause of the behavior. Additionally, we highly recommend utilizing our [official forum](https://discord.gg/rgGYfeYW3N) before to report a bugs here, as it provides a more structured environment for troubleshooting and resolution. Thank you for the collaboration.
