### ISSUE TITLE
Choose WebRTC ports based on client IP address?

### ISSUE THREAD

**Issue by AgentSmith0** [miroslavpejic85/mirotalksfu#147]
I have the problem that audio and voice transmission only works from outside the network. Port forwarding blocks the WebRTC ports for inbound traffic. So is it possible to choose another port range only for local network clients (based on IP)?

**Comment by miroslavpejic85** [comment]
**Seek Community Support**: please for questions, it's advisable to seek assistance from the Mirotalk community. Join with us on the [help & support channel](https://discord.gg/rgGYfeYW3N) on Discord.  

Thank you.
