### ISSUE TITLE
If chatGPT is disabled, it shouldn't appear on the chat list

### ISSUE THREAD

**Issue by TehPeGaSuS** [miroslavpejic85/mirotalksfu#148]
# Feature request

When [this](https://github.com/miroslavpejic85/mirotalksfu/blob/main/app/src/config.template.js#L256) is set to `false`, then ChatGPT shouldn't appear on the chat list, since it's rather confusing to most of the users.

## Pros

N/A

## Additional context

N/A

**Comment by miroslavpejic85** [comment]
Hello @TehPeGaSuS,

While it's `simple to implement`, choosing not to display the ChatGPT feature when it's disabled might `lead users to believe that the feature doesn't exist at all`. Therefore, we already include a message notification in the interface indicating that the feature is disabled. This ensures that users understand why the feature isn't available and helps maintain transparency in the user experience. 

We can continue our discussion about channel suggestions in our community forum. Click [here](https://discord.gg/rgGYfeYW3N) to join. 

Please interact with others in the forum before opening an issue here.

Thank you!

**Comment by miroslavpejic85** [comment]
```js
ui: {
    /*
        Toggle the visibility of specific HTML elements within the room
    */
    buttons: {
        // Other settings...
        chat: {
            // Other chat settings...
            chatGPT: true, // Set to false to hide the chatGPT section in the chat
        },
        // Other settings...
    },
},
```

**Comment by TehPeGaSuS** [comment]
I really appreciate it 😀
