### ISSUE TITLE
After joining a room, side bar buttons don't work as expected on mobile.

### ISSUE THREAD

**Issue by Rubonnek** [miroslavpejic85/mirotalksfu#150]
# Bug Report

## Describe the bug

None of the buttons seem to work on Android (mobile).

## To reproduce

Join a room at [sfu.mirotalk.com](https://sfu.mirotalk.com/) on Android with Chrome and attempt to push any of the side buttons to open/close the chat/whiteboard/mic/camera/etc.

## Expected behavior

User is able to push  side bar buttons and the buttons react accordingly.

## Screenshots

N/A - the buttons simply grow transparent when tapping on them.

## Desktop - Mobile

Please complete the following information:

 - Device or OS: Android 14 - LineageOS 21 (March 15, 2024)
 - Browser: Chrome version 123.0.6312.99

**Comment by miroslavpejic85** [comment]
![mirotalk-sfu-android-14](https://github.com/miroslavpejic85/mirotalksfu/assets/70838434/55d5f173-7b29-46c6-bb31-a17b211d572c)

Following our recent tests, we have concluded that there are no issues reported as per your description. We have thoroughly examined the system and found no discrepancies.

In addition, we kindly remind you to ensure that your browser is regularly updated to the latest version. This ensures optimal performance and security enhancements. Should you have any further queries or concerns, feel free to join our **[community forum](https://discord.gg/rgGYfeYW3N)**.

**Comment by Rubonnek** [comment]
I should add this issue doesn't happen with the `p2p` version of mirotalk, just with sfu.

**Comment by miroslavpejic85** [comment]
> Hmmm... perhaps it's an issue with LineageOS 21 (March 15, 2024) webview I suppose.

For LineageOS 21 testing purposes, it is imperative to utilize real devices over emulators and refrain from relying solely on WebView simulation. An observation worth noting is the incomplete loading of buttons, indicative of potential internal errors. These anomalies could be further elucidated by scrutinizing the Web console logs for a comprehensive understanding of the underlying issues.

Without additional logs it becomes a challenge to understand what the problem may be related to your current environment compared to a real environment.

> \[!NOTE]
>
> LineageOS is primarily used by enthusiasts and developers who are interested in customizing their Android devices beyond what is typically offered by the manufacturer. While some "usual" users may also use LineageOS, it's not as common among mainstream users compared to the stock operating system provided by device manufacturers.
>
> Typically, users who install LineageOS are comfortable with the process of unlocking bootloaders, rooting their devices, and flashing custom firmware. These users may include hobbyists, developers, or individuals seeking specific features or improvements not available in the stock firmware.
>
> For the average user who is not interested in tinkering with their device's software, sticking with the manufacturer's provided operating system is more common and often recommended for simplicity and stability.

**Comment by Rubonnek** [comment]
> For LineageOS 21 testing purposes, it is imperative to utilize real devices over emulators and refrain from relying solely on WebView simulation.

In my capture I  used a real device, a Pixel 5a. The capture was done through `scrcpy`. I did use Chrome, but I assume it uses Webview. I'm not very familiar Android nor Webview.

**Comment by miroslavpejic85** [comment]
When you mention using Chrome, it's likely that the web pages you accessed were displayed using WebView, which is a component in Android that allows apps to display web content.

If you have any specific questions about Android or WebView, feel free to ask to our [community forum](https://discord.gg/rgGYfeYW3N)!

Cheers.

**Comment by Rubonnek** [comment]
I'm not sure why this issue has been closed -- this issue also happens on a real physical device (a Pixel 3) using stock Android 12 and Chrome version 123.0.6312.99.

I've been trying to get some logs or a trace but I'm having issues with adb.
