### ISSUE TITLE
Improve UX

### ISSUE THREAD

**Issue by senavi888** [miroslavpejic85/mirotalksfu#151]
Hi!
Thanks for your great product! I haven't found the best quality of both audio and video yet. I would like to make a suggestion that will improve the experience of people who use the mirotalks

The problem is the notification when the conference recording starts. It takes the attention away from the conference too much. Many people leave the room by mistake. I suggest simplifying these screens, I sketched out my idea on purpose. I've attached a picture.

![User Story Map Framework - Frame 1(1)](https://github.com/miroslavpejic85/mirotalksfu/assets/161348858/b4a2e1ab-0088-468c-b453-bc2f369c1350)

I showed an example on mobile, but the same applies to the desktop version.

People get confused about which button to press when agreeing to the recording and leave the room. Those who pressed the right one, then do not know how to close the chat window. Thereby making them nervous.

It would be cool if you could do the same as you do in other conferences, like big blue button, MS teams and etc.

Thanks!

**Comment by senavi888** [comment]
Or don't use the button in the notification at all.  And show the text:

"Moderator has enabled conference recording, by remaining in the room you agree to this."

That's it, that's all you need. Recording conferences is a frequent function in training, and everyone is used to it. Use the same notification module that you already have.

**Comment by senavi888** [comment]
If you can tell me how to disable this notification in the configuration, I would be very grateful, it is very distracting for users.

**Comment by miroslavpejic85** [comment]
Hi @senavi888,

Thank you for the suggestion and the kind words! It's great to hear that you're enjoying the product. Improving user experience is always a priority, and your feedback is invaluable in that regard. Should be done.

![mirotalk-sfu-rec-notify](https://github.com/miroslavpejic85/mirotalksfu/assets/70838434/b2c56428-e372-40cf-82e2-06e88b1e3081)

> If you can tell me how to disable this notification in the configuration, I would be very grateful, it is very distracting for users.

To disable the chat display during a recorded conference and respect user privacy, follow this steps:

1. Click on the `dropdown menu` located at the `top right` corner of the `chat` interface.
2. From the dropdown menu, `deselect` the option labeled 'Disable chat shown on new message.'
3. Once deselected, the chat will no longer be visible, ensuring a less distracting experience for users during the conference while still retaining the notification message popup to respect their privacy.

These settings will persist for future conferences, providing a seamless experience. 

Join us on Mirotalk's vibrant **[WebRTC community forum](https://discord.gg/rgGYfeYW3N)**! Share insights, connect with experts, and explore the latest in real-time communication technology. Your voice matters. 

See you there!
Miroslav

**Comment by senavi888** [comment]
I'm very glad that you listen to users! Thank you!

**Comment by senavi888** [comment]
You already did it! I updated the app, thank you so much! Best news of the morning!
