### ISSUE TITLE
Bitrate tuning. Killer feature.

### ISSUE THREAD

**Issue by senavi888** [miroslavpejic85/mirotalksfu#152]
I'm with ideas to improve the flexibility of the product. I have been looking for 3 weeks for a solution for stereo CD quality audio in conferencing.
Big Blue Button - I couldn't set up stereo audio, spent a week poking around in configs.
Jitsi - I couldn't set up recording by default, for this i installed from quick install script (found on github), but there I couldn't enable stereo in some browsers.

There is not a single sane option for this task except Mirotalk. 

Perhaps this can be added in the advanced audio setup options, where in the interface selected the number of channels and the audio sampling rate. 
And in the config you can set this bitrate by default for everyone

Make the default 32kbs for crystal voice sound, for example, but give the possibility to choose:

8000
16000
32000
48000
64000
128000
256000
320000

Opus RED: true\false

About Opus Red: https://webrtchacks.com/red-improving-audio-quality-with-redundancy/ 

I think for streaming events, meetings, music learning this would be a killer feature with a working stereo on the market.

**Comment by miroslavpejic85** [comment]
Come join us in our **[community forum](https://discord.gg/rgGYfeYW3N)** channel dedicated to `ideas and suggestions`! Here, we can collectively brainstorm and discuss all things MiroTalk. Let's maintain our focus on this project and avoid veering off-topic (`rule 7`). Moreover, it's worth noting that some of the Simple Rate methods mentioned may not be widely used in standard audio applications. Your participation in the forum is eagerly awaited. Let's move this to the forum, thank you!
