### ISSUE TITLE
I have a problem installing MiroTalk on AWS

### ISSUE THREAD

**Issue by hrauvc** [miroslavpejic85/mirotalksfu#158]
# MiroTalk forum

First I am going to share how I have the infrastructure

## 1. I have an Ec2 instance on a private subnet
![image](https://github.com/miroslavpejic85/mirotalksfu/assets/12868727/77bf70f0-8180-4e06-9e88-94802bb7a2ab)

## 2. These are the security groups associated with the instance
![image](https://github.com/miroslavpejic85/mirotalksfu/assets/12868727/09c001f2-81e4-438a-ad25-21dda78634a0)

## 3. I have the load balancer pointing to my instance
![image](https://github.com/miroslavpejic85/mirotalksfu/assets/12868727/c2b07d8c-a630-4ec4-b8a2-ef545e88d50d)

And so are the listening agents
![image](https://github.com/miroslavpejic85/mirotalksfu/assets/12868727/ff3bdbd5-e7ae-41cd-8418-ceb0c18d55b9)

## 4. The target group:
![image](https://github.com/miroslavpejic85/mirotalksfu/assets/12868727/fbe755ad-4334-4194-9d44-ee0c193160d9)

And its destiny 
![image](https://github.com/miroslavpejic85/mirotalksfu/assets/12868727/18d38d38-7465-4760-8f04-609c58e4dacb)

On route 53 I point to the load balancer:
![image](https://github.com/miroslavpejic85/mirotalksfu/assets/12868727/2f1b3614-c3a5-4a1d-bd7b-d98cd815f339)
![image](https://github.com/miroslavpejic85/mirotalksfu/assets/12868727/448ce016-ba92-4808-91be-e37ed10177f8)

The app works
![image](https://github.com/miroslavpejic85/mirotalksfu/assets/12868727/3a3aca22-3570-40b4-9316-62873390c5b8)

And Start the meeting
![image](https://github.com/miroslavpejic85/mirotalksfu/assets/12868727/6efa03e3-3968-49b9-b78a-de7a09b3481f)

But after a moment this happens:
![image](https://github.com/miroslavpejic85/mirotalksfu/assets/12868727/53f0a9c7-8e70-4bb2-adc8-2d3b1558a884)

And if another user enters it looks like this:
![image](https://github.com/miroslavpejic85/mirotalksfu/assets/12868727/41237f89-eccb-4dff-b150-5f6fca113550)

No errors here:
![image](https://github.com/miroslavpejic85/mirotalksfu/assets/12868727/85414908-5cc8-4daa-b067-0cf06f881d91)

This is my nginx file:
`# HTTP — proxy all requests to the Node app
server {
    listen 80;
    listen [::]:80;
    server_name meet.dbcloud.academy;

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://localhost:3010/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}`

I have not placed the ssl here since otherwise it will get into a loop with AWS

**Comment by miroslavpejic85** [comment]
For help & support, please refer to the forum mentioned in the README. There, you’ll find answers to similar questions I have already addressed. Make sure to set the inbound rules, including port ranges, and use the EC2 elastic IP as the announcedAddress in the config.js. For more details, visit the forum. Cheers!
