### ISSUE TITLE
Support iOS/Android/Windows/macOS native application

### ISSUE THREAD

**Issue by portsip** [miroslavpejic85/mirotalksfu#159]
# Feature request

Hi, could mirotalks support the iOS/Android/Windows/macOS native application? Currently seems the client can only run with broswer.

**Comment by miroslavpejic85** [comment]
MiroTalk can indeed support iOS, Android, Windows, and macOS as a Progressive Web App (PWA), which offers several benefits. As a PWA, MiroTalk can be added to the home screen of mobile devices, providing a more app-like experience without the need for distribution through app stores. Here are the advantages of keeping MiroTalk as a PWA:

Pros of MiroTalk as a PWA

	1.	Cross-Platform Compatibility:
	•	PWAs work across different operating systems (iOS, Android, Windows, macOS) without the need for separate codebases for each platform.
	2.	Ease of Updates:
	•	Updates can be pushed directly through the web, ensuring all users have the latest version without needing to download updates from app stores.
	3.	Cost-Effective Development:
	•	Developing and maintaining a single PWA is more cost-effective than building and supporting native apps for multiple platforms.
	4.	Offline Capabilities:
	•	PWAs can work offline or with poor network conditions using service workers, offering better reliability.
	5.	No Installation Required:
	•	Users can access MiroTalk directly from their browser without a lengthy download and installation process. They can also add it to their home screen for easy access.
	6.	Improved Performance:
	•	PWAs load faster and offer a smoother user experience similar to native apps, thanks to caching and other modern web technologies.
	7.	SEO Benefits:
	•	Being web-based, PWAs can be indexed by search engines, improving discoverability.
	8.	App-Like Experience:
	•	Once added to the home screen, PWAs run in a standalone window and offer a user experience comparable to native apps, including full-screen mode and push notifications.

Cheers.

**Comment by miroslavpejic85** [comment]
MiroTalk can effectively support iOS, Android, Windows, and macOS as a **[Progressive Web App](https://www.youtube.com/watch?v=Z8MjdQGyjfA)** (PWA), offering numerous advantages. By leveraging the PWA technology, MiroTalk can be **[added to the home](https://www.youtube.com/watch?v=SGgu0LTVyY0)** screens of mobile devices, delivering an app-like experience without the need for distribution through app stores. Here are the key benefits of maintaining MiroTalk as a PWA:

**Advantages of MiroTalk as a PWA**

1. **Cross-Platform Compatibility**:
   - PWAs function seamlessly across various operating systems (iOS, Android, Windows, macOS) without requiring separate codebases for each platform.

2. **Ease of Updates**:
   - Updates can be deployed directly through the web, ensuring all users have the latest version without needing to download updates from app stores.

3. **Cost-Effective Development**:
   - Developing and maintaining a single PWA is more economical than building and supporting native apps for multiple platforms.

4. **Offline Capabilities**:
   - PWAs can operate offline or under poor network conditions using service workers, providing enhanced reliability.

5. **No Installation Required**:
   - Users can access MiroTalk directly from their browser without a lengthy download and installation process. They can also add it to their home screen for convenient access.

6. **Improved Performance**:
   - PWAs load faster and offer a smoother user experience similar to native apps, thanks to caching and other modern web technologies.

7. **SEO Benefits**:
   - As web-based applications, PWAs can be indexed by search engines, improving discoverability.

8. **App-Like Experience**:
   - Once added to the home screen, PWAs run in a standalone window and provide a user experience comparable to native apps, including full-screen mode and push notifications.

Cheers.
