### ISSUE TITLE
Only host recording not working

### ISSUE THREAD

**Issue by hrauvc** [miroslavpejic85/mirotalksfu#163]
# Bug Report: Participants Can Record Despite "Only Host" Setting

## Description

When acting as a presenter in a meeting with the "Only Host" option enabled, participants are still able to see and use the recording option, which contradicts the intended functionality of this setting.

## Expected Behavior

When the "Only Host" option is active, the recording option should be restricted to the host only. Participants should not have the ability to see or use the recording feature.

## Steps to Reproduce

1. Start a meeting as a host.
2. Enable the "Only Host" option.
3. Join the meeting as a participant.
4. Observe that the recording option is still available for the participant.

## Actual Behavior

Despite enabling the "Only Host" setting, participants can still access the recording option.

![image](https://github.com/user-attachments/assets/eead3897-0d87-4791-8d4f-f10d3bc8c497)

**Comment by miroslavpejic85** [comment]
Hi hrauvc,

Thank you for your feedback. 

We tested the functionality on our **[live demo](https://sfu.mirotalk.com)** and can confirm that the issue described is not present.

![mirotalk-sfu-presenter-rec-only](https://github.com/user-attachments/assets/cf1fb226-f1fa-4a77-9b44-e66e47d5fe65)

To clarify the functionality:

1. The individual designated as the presenter in the `config.js` file, or the first person to join the room if not specified, will assume the presenter role.
2. All other users will have the guest role.
3. The presenter, even if recording options are disabled, will still be able to see the recording button and start recording. The restrictions on recording are applicable only to the other participants, not the presenter.

For any further questions or clarifications, we encourage you to visit our **[community forum](https://discord.gg/rgGYfeYW3N)**. Engaging there might help resolve misunderstandings about the application's functionality more efficiently.

Just a few suggestions: 
- Ensure you are using the **latest** version of MiroTalk SFU.
- Clear your browser cache and update your browser to the latest version.
- If you do not encounter the issue on our live demo, as it appears to be functioning correctly, please refrain from opening an issue here. Instead, use the community forum for further discussions and assistance.

Thank you for your collaboration.

Best regards,  
Miroslav
