### ISSUE TITLE
i want to improve recorded video result.

### ISSUE THREAD

**Issue by haseebkhalid907** [miroslavpejic85/mirotalksfu#166]
### Describe the bug

i want to improve recorded video result.

### Steps to reproduce

i want to improve recorded video result.

### Expected behavior

i want to improve recorded video result.

### Device

- [ ] Android
- [ ] iPhone
- [ ] Linux
- [ ] Mac
- [ ] Windows

### Browser

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Android browser
- [ ] iOS browser
- [ ] Other desktop browser

### Reproducibility

Yes

**Comment by miroslavpejic85** [comment]
This is not a bug. For ideas and suggestions, please share your thoughts in the  dedicated channel on the [community forum](https://discord.gg/rgGYfeYW3N). Thank you!
