### ISSUE TITLE
Opening links from the chat kicks you out of the meeting

### ISSUE THREAD

**Issue by avatar1024** [miroslavpejic85/mirotalksfu#168]
### Describe the bug

If some one put a link in the chat, the when clicking on a link in the chat, the link loads on the same page of the meeting and so I get kicked out of the meeting. The default behaviour should be to open links in a new window.

Tested with Firefox, MiroTalk SFU 1.5.83 (Cloudron)

### Steps to reproduce

1. Create a meeting room
2. Have someone join the room
3. Open the chat window
4. Post a link to a webpage
5. Click on the link

### Expected behavior

The link open in a new window

### Device

- [X] Android
- [ ] iPhone
- [X] Linux
- [ ] Mac
- [ ] Windows

### Browser

- [ ] Chrome (or Chromium based)
- [X] Firefox
- [ ] Safari
- [ ] Android browser
- [ ] iOS browser
- [ ] Other desktop browser

### Reproducibility

Yes

**Comment by bitkarrot** [comment]
I managed to fix this in our forked code base for firefox but it still seems to persist on Brave browser. Unclear why.

**Comment by miroslavpejic85** [comment]
Hi @avatar1024, Thank you for bringing this to our attention. The issue has been addressed and resolved in the attached commit.

**Comment by miroslavpejic85** [comment]
![mirotalk-sfu-fix-target](https://github.com/user-attachments/assets/f5a1b325-cfb6-45b7-930f-1b61c2e5a315)
