### ISSUE TITLE
Private Messaging fail when new peer joins the room.

### ISSUE THREAD

**Issue by Yeghro** [miroslavpejic85/mirotalksfu#169]
### Describe the bug

if 2 users are private messaging each other in a room and a new peer joins while they are in the middle of the private conversation, any message sent right after the new peer joins is sent to public chat rather than privately to the peer it was meant to be sent to.

### Steps to reproduce

Create a room with 2 users and begin a private chat and keep the private chat window open while you open another tab or windows to login in with a third user.  After logging in with the new (3rd user) go back to the private message window opened prior with the original users and send a private message.  
Rather than it going to the intended peer, it will show in the public chat.

### Expected behavior

The private message should only be sent to the intended peer and not public chat where anyone can see it.

### Device

- [ ] Android
- [ ] iPhone
- [ ] Linux
- [ ] Mac
- [X] Windows

### Browser

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Android browser
- [ ] iOS browser
- [ ] Other desktop browser

### Reproducibility

Yes

**Comment by miroslavpejic85** [comment]
![mirotalk-sfu-private-messages-fix](https://github.com/user-attachments/assets/8b7cfd5d-fcdb-42c9-a2ce-ffeb95155d7c)

**Comment by Yeghro** [comment]
My apologies.  After testing again today I don't see the problem anymore.   Must've been some mistake on my end.

**Comment by miroslavpejic85** [comment]
> My apologies. After testing again today I don't see the problem anymore. Must've been some mistake on my end.

The bug was indeed present as you described, but it has been fixed in [this commit](https://github.com/miroslavpejic85/mirotalksfu/commit/d177bbb6b0c1ff0d32a6255fbbb622eed25f4bc6) ;)

**Comment by Yeghro** [comment]
Oh that's great to hear.   I was afraid I had made a mistake.  Thank you.

**Comment by Yeghro** [comment]
Seem like this bug has return with your latest updates to the code.  It happens in both public and private text chat.

**Comment by miroslavpejic85** [comment]
In our [Live demo](https://sfu.mirotalk.com)?

**Comment by Yeghro** [comment]
> In our [Live demo](https://sfu.mirotalk.com)?

Yes I tested it on sfu.mirotalk.com

open a chat between 2 peers , send a few messages and keep the chat window open, then enter in with a new 3rd user and go back to user 1 or user 2 and try to send a message.  It refuses to send until you click on either public chat or a peer, after which it seems to work again.

**Comment by miroslavpejic85** [comment]
Should be fixed, can you confirm? Thank you!

**Comment by Yeghro** [comment]
Confirmed fixed.

> Should be fixed, can you confirm? Thank you!
