### ISSUE TITLE
Add Mattermost integration

### ISSUE THREAD

**Issue by miroslavpejic85** [miroslavpejic85/mirotalksfu#170]
### Feature request

Implement a feature that allows users to initiate MiroTalk SFU meetings directly from **[Mattermost](https://mattermost.com)** using a dedicated slash command (e.g., `/sfu`). This command should trigger a callback to an Express server, which will handle the creation of the SFU meeting room.

### Pros

1. **Improved Workflow**: Streamlines the process of starting SFU meetings, reducing the need to switch between applications.
2. **Enhanced Collaboration**: Facilitates quicker communication and collaboration among team members by allowing them to initiate video calls seamlessly.
3. **User Convenience**: Simplifies the user experience by integrating video conferencing capabilities directly into the Mattermost platform.
4. **Increased Adoption**: Encourages more users to utilize MiroTalk SFU features as it becomes more accessible within the tools they already use.
5. **Centralized Notifications**: Provides a centralized location for notifications and updates related to SFU meetings, enhancing team coordination.

### Additional context

As done in **[MiroTalk P2P](https://github.com/miroslavpejic85/mirotalk/issues/243#issuecomment-2438759606)**

**Comment by miroslavpejic85** [comment]
### Setting Up a Slash Command in Mattermost

1. Navigate to **Main Menu > Integrations > Slash Commands** in Mattermost.
2. Click on **Add Slash Command** and configure the following settings:
   - **Title**: Enter a descriptive title (e.g., `SFU Command`).
   - **Command Trigger Word**: Set the trigger word to `sfu`.
   - **Callback URLs**: Enter the URL for your Express server (e.g., `https://yourserver.com/mattermost`).
   - **Request Method**: Select **POST**.
   - **Enable Autocomplete**: Check the box for **Autocomplete**.
   - **Autocomplete Description**: Provide a brief description (e.g., `Get MiroTalk SFU meeting room`).

3. Save the slash command and **copy the generated token**; you will need it for your server setup.

4. **Update the MiroTalk SFU `config.js` File**: 
   - Add the new parameters required for your configuration.

```env
    api: {
        allowed: {
            mattermost: true,
        },
    },
    mattermost: {
        enabled: false,
        serverUrl: 'YourMattermostServerUrl',
        username: 'YourMattermostUsername',
        password: 'YourMattermostPassword',
        token: 'YourMattermostToken',
        commands: [
            {
                name: '/sfu',
                message: 'Here is your meeting room:',
            },
        ],
        texts: [
            {
                name: '/sfu',
                message: 'Here is your meeting room:',
            },
        ],
    },
```

![mirotalk-sfu-mattermost](https://github.com/user-attachments/assets/7306d3c3-13a1-4a6e-abf2-881d0b217639)

**Comment by karthikindia** [comment]
can i integrate mirotalksfu with mattermost too ?
