### ISSUE TITLE
Peer volume control 

### ISSUE THREAD

**Issue by Yeghro** [miroslavpejic85/mirotalksfu#171]
### Feature request

Would nice for users to be able to control the volume of individual peers on mobile.  Perhaps a more mobile friendly peer menu for buttons and volume control.

example:
![image](https://github.com/user-attachments/assets/47d19acb-428f-48db-8d10-9478f63d544c)

### Pros

Users would be able to mute or lower volume of peers as to isolate a specific peer's audio so the user can control how many peers they are listening to at any given time when dealing with many peers.  Similar to how desktop functions. 

### Additional context

image is from HiveTalk fork.

**Comment by miroslavpejic85** [comment]
![mirotalk-sfu-mobile-volume](https://github.com/user-attachments/assets/c8d09af3-d79a-4b3a-a70a-b78de07b9ead)

**Comment by Yeghro** [comment]
Would it be possible to get volume control for remote peers to work for everyone that is taking part in the stream.  Not just volume control for shared media but also volume control over peer mic audio as well?

This would give everyone more control over all audio coming in from all/any peers.

**Comment by miroslavpejic85** [comment]
## Added Complete Volume Control

1. **Distinguishing Audio Sources**: I identified and differentiated between audio streams from microphones (producers) and shared media (consumers).

2. **Synchronizing Volume Changes**: I used the existing `emitCmd` mechanism to broadcast volume updates for both producer and consumer audio streams. I ensured that all clients listen for these updates and adjust the volume of the corresponding audio elements accordingly.

3. **Managing Producer Audio**: I extended the logic to handle volume control for producer audio as well. This involved managing audio elements for peer microphones and applying the necessary volume adjustments.

> \[!NOTE]
>
> When a producer changes the volume from the default value of 100, I disabled the volume control input on the consumer side to prevent further adjustments. Otherwise, I kept the input enabled when the volume remained at 100.
