### ISSUE TITLE
Chromium Crash

### ISSUE THREAD

**Issue by MORRA-RM** [miroslavpejic85/mirotalksfu#172]
### Describe the bug

When I try to send a file to a user in chat -- if I add a space after the file it crashes the browser.

### Steps to reproduce

.

### Expected behavior

.

### Device

- [ ] Android
- [ ] iPhone
- [ ] Linux
- [ ] Mac
- [ ] Windows

### Browser

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Android browser
- [ ] iOS browser
- [ ] Other desktop browser

### Reproducibility

Yes

### Additional context

hey man. im not sure how to do this the right way but i was asked to send these to you. thank you for your patience 
![Screenshot 2024-11-01 at 7 39 15 pm](https://github.com/user-attachments/assets/feb81d86-d72c-4254-9d83-db1efd41c168)

**Comment by miroslavpejic85** [comment]
@MORRA-RM 

**Reproducibility: Yes**

Means you have successfully reproduced the issue on our official [Live demo](https://sfu.mirotalk.com) ?

To assist us in further investigating this matter, could you please provide the following information in the form?

1. **Steps to Reproduce**:
   - Please outline the exact steps necessary to replicate the issue. Be as specific as possible with each action. For example:
     1. Open the application in [specific browser].
     2. Navigate to [specific page or feature].
     3. Click on [specific button or link].
     4. Observe the behavior (e.g., error message...).

2. **Device and Browser Information**:
   - Specify the type of device you used (e.g., desktop, tablet, smartphone).
   - Include the operating system (e.g., Windows, Linux, macOS, iOS, Android).
   - Indicate the browser and version (e.g., Chrome 94, Safari 15).

3. **Additional Context**:
   - If applicable, please attach any relevant screenshots or logs that could help illustrate the problem, especially attach here the `file that caused the crash`.

Once you have organized this information, please update the form.

## Note

The attached screenshot does not match the file-sharing feature in our current version.

![mirotalk-sfu-file-sharing](https://github.com/user-attachments/assets/1e9846cb-da01-446f-ad34-49652cfadf46)

Thank you!

**Comment by MORRA-RM** [comment]
ok. this originally came from [maybe](https://github.com/ArthurAmendt) on hivetalk. im not a programming guy so ill ask him.

**Comment by miroslavpejic85** [comment]
> ok. this originally came from [maybe](https://github.com/ArthurAmendt) on hivetalk. im not a programming guy so ill ask him.

It's important to check whether the issues you encounter are directly related to the *Live demo* or the *original source code*. If the problem is from a customized or derived project, it could be due to changes made that introduced bugs. Make sure to verify this before reporting an issue.  Thank you for understanding!

**Comment by miroslavpejic85** [comment]
Hi @MORRA-RM,

We are unable to reproduce the problem you reported.

For future communications, we kindly ask that you compile all the relevant form inputs and provide detailed steps to reproduce the issue, as simply stating `.` does not assist us in our debugging process :)

Additionally, we encourage you and anyone interested to join our [community forum](https://discord.gg/rgGYfeYW3N), where we can openly discuss potential and confirmed bugs before to address them individually here.

Thank you for your understanding, and we hope you have a wonderful weekend!

Best regards,
Miroslav
