### ISSUE TITLE
 Mobile safari doesn’t auto play videos when shared to me but it does auto play when I share it

### ISSUE THREAD

**Issue by MORRA-RM** [miroslavpejic85/mirotalksfu#173]
### Describe the bug

.

### Steps to reproduce

.

### Expected behavior

.

### Device

- [ ] Android
- [x] iPhone
- [ ] Linux
- [ ] Mac
- [ ] Windows

### Browser

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [x] Safari
- [ ] Android browser
- [ ] iOS browser
- [ ] Other desktop browser

### Reproducibility

Yes

**Comment by miroslavpejic85** [comment]
Safari's requirement for user interaction to unmute videos ensures a better, more controlled user experience. It prevents unexpected sound, reduces data and battery usage, and addresses privacy concerns. This behavior is in line with autoplay policies enforced by other major browsers like Chrome, but Safari has stricter enforcement, especially on mobile.

![mirotalk-sfu-YT-safari-mobile](https://github.com/user-attachments/assets/ab938d95-b3b4-42a1-aed1-0b9c85a996ba)

**Comment by MORRA-RM** [comment]
Bro you are a legend. LOL do you sleep. Again thank you so much
