### ISSUE TITLE
Longer hand raise time

### ISSUE THREAD

**Issue by MORRA-RM** [miroslavpejic85/mirotalksfu#174]
### Feature request

![Screenshot 2024-11-01 at 7 47 53 pm](https://github.com/user-attachments/assets/f4d70393-f4cd-4e04-9fdf-b432e7e08f6a)

### Pros

.

**Comment by miroslavpejic85** [comment]
Improved the behavior of the Raise Hand status to ensure it remains persistent even when the camera is turned on or off. The Raise Hand status will now always be visible within the video feed or chat. Additionally, it can be easily managed and filtered using a dedicated button.

![mirotalk-sfu-raise-hand-fix](https://github.com/user-attachments/assets/053a3b32-d479-4d7f-97bd-a6f41cfcebb0)

**Comment by MORRA-RM** [comment]
Damn bro you rock. Bitkarrot told me you were awesome. I dont know anything about coding or github. im just trying to help out and learn. Thank you for being so patient with me. You can be sure any entries I make in the future will be better. Keep up the great work
