### ISSUE TITLE
Recording Download as .mp4 format

### ISSUE THREAD

**Issue by MORRA-RM** [miroslavpejic85/mirotalksfu#176]
### Feature request

Current Recording download is in .webm format. Was wondering if recordings could be saved as .mp4. Or maybe a choice given. 

### Pros

This would alleviate having to convert to .mp4. 

### Additional context

Some users are asking for this feature because they are saying it takes longer to edit a .webm then an .mp4. It might be because the .mp4 is more familiar. 
Thank you

**Comment by miroslavpejic85** [comment]
Opting for `.webm` provides several benefits that make it particularly suitable for web applications. Here are some advantages of using the WebM format:

1. **Web Optimization**: WebM is tailored for efficient streaming, offering low latency and quick load times, making it perfect for live and online video content.
2. **Open and Royalty-Free**: Utilizing VP8/VP9 for video and Opus for audio, WebM is free from licensing fees, making it cost-effective for developers.
3. **Efficient Compression**: WebM files are smaller in size without sacrificing quality, which helps reduce storage needs and bandwidth usage.
4. **High-Quality Video**: Despite the smaller file sizes, WebM maintains high-definition quality, supporting resolutions up to 4K and beyond.
5. **Broad Browser Support**: Most modern browsers, including Chrome, Firefox, and Edge, offer native support for WebM, eliminating the need for additional plugins.
6. **Future-Proof**: WebM continues to evolve, with ongoing development to support new codecs like AV1, enhancing compression efficiency and quality over time.
7. **Transparency Features**: WebM supports alpha channels, enabling videos with transparent backgrounds for web overlays and interactive elements.

### Special Considerations for Safari
While WebM excels in many aspects, it is not fully supported on Safari. To ensure compatibility across all platforms, especially on Apple devices, recorded videos in Safari are saved in the `.mp4` format.

### H.264

![mirotalk-sfu-webm](https://github.com/user-attachments/assets/c1c6d1e8-27af-4ad9-b723-6c65438e46e5)

You can prioritize recording to use H.264 as the preferred video compression standard for the following reasons:
- **Universal Compatibility**: H.264 is widely supported across all major browsers and platforms, including Safari, ensuring reliable playback.
- **Efficient Compression**: It delivers high-quality video at lower bitrates, making it ideal for streaming and reducing storage requirements.
- **Hardware Acceleration**: Many devices come with built-in support for H.264, improving playback performance and reducing battery consumption.

### Converting WebM to MP4
If you need to convert a WebM file to MP4, you can easily do so using `ffmpeg`. Here’s how:

```bash
# Install ffmpeg
sudo apt install -y ffmpeg

# Convert WebM to MP4
ffmpeg -i input.webm output.mp4
```

**Comment by MORRA-RM** [comment]
This is perfect. Thank you
