### ISSUE TITLE
Background image 

### ISSUE THREAD

**Issue by haseebkhalid907** [miroslavpejic85/mirotalksfu#178]
### Feature request

I want a feature where 4-5 people are connected in a call, and all of them have the same background, similar to this image. We should be able to zoom out and set the camera, creating an interface that looks just like this image.
![WhatsApp Image 2024-11-07 at 4 56 57 PM](https://github.com/user-attachments/assets/d565d579-dbb0-4c37-9da3-f5a1559f69ac)

### Pros

![WhatsApp Image 2024-11-07 at 4 56 57 PM](https://github.com/user-attachments/assets/d2ca6755-7d3d-40c1-9198-ca2d6c9b27cf)

**Comment by miroslavpejic85** [comment]
Please avoid using `"I WANT"` statements. Instead, consider the potential benefits and pros of MiroTalk SFU for the `broader community`. For **ideas and suggestions**, please use the designated channels in the [community forum](https://discord.gg/rgGYfeYW3N).

Thank you for your understanding!
