### ISSUE TITLE
Live stream like facebook, instagram

### ISSUE THREAD

**Issue by haseebkhalid907** [miroslavpejic85/mirotalksfu#179]
### Feature request

I want two types of people to be able to connect in the call, similar to a Facebook or Instagram live. This means one type would be the presenters, and the other type would be viewers who can watch the live session, just like in this picture.

### Pros

![image](https://github.com/user-attachments/assets/795a082d-ee22-4719-99ac-86e037e3501b)

**Comment by miroslavpejic85** [comment]
Please avoid direct pings whenever possible.

The room broadcasting options are already available (one-to-many):

![mirotalk-sfu-room-broadcasting](https://github.com/user-attachments/assets/94c773eb-74ee-4782-b4d4-5ad395a19384)

MiroTalk SFU also supports RTMP streaming with versatile input options, including:

![mirotalk-sfu-rtmp](https://github.com/user-attachments/assets/922ad330-eddf-4f95-a36c-b96451c23cc6)

- `File`: You can broadcast a pre-recorded video file.
- `URL`: Stream content from an external URL source.
- `Camera`: Broadcast live using your camera feed.
- `Open Windows`: Share any open window for live streaming.
- `Screen Sharing`: Stream your entire screen.

These capabilities can be utilized to create a comprehensive broadcasting platform, allowing real-time broadcasts and the option to stream scheduled or looped recorded content.

Thank you for your cooperation!
