### ISSUE TITLE
Question: whats the difference between this repo and mirotalk

### ISSUE THREAD

**Issue by jhjacobs81** [miroslavpejic85/mirotalksfu#18]
Because we are looking to replace Jitsi Meet, and i ran into both mirotalk and mirotalksfu

**Comment by jhjacobs81** [comment]
Awesome! and what a quick response time :)

i will give SFU a go. how about changing the looks etc? any documentation?

**Comment by jhjacobs81** [comment]
thank you :) i will have a look on it

**Comment by MrRulf** [comment]
Hi, I found this project and it looks really nice, but I struggle to find the differences to jitsi, matrix or mattermost, since this issue talks about replacing jitsi i was hoping maybe you could give me some hints ^^

**Comment by jhjacobs81** [comment]
Well, thats not the same as my original question. As i was asking about Mirotalk SFU and the "normal" Mirotalk.

Matrix is a protocol with which you can build a chat solution, Mattermost is a chat solution.

Jitsi is software to build videoconferences with, and so is Mirotalk. Depending on what you are trying to do you choose one thing or the other.

**Comment by MrRulf** [comment]
okay, but how does the tech behind mirotalk differ from what is used in the matrix protocol for audio/video chat and how is it different from jitsi, so that i know if i choose jitsi or mirotalk, thats more what im confused about ^^"

**Comment by jhjacobs81** [comment]
I dont think i understand the question :)

Matrix is a protocol, it has nothing to do with this discussion. 

Jitsi is build on different components to make things work. This makes Jitsi much bigger then MirotalkSFU (which is simpeler to use) but i believe both are based around WebRTC.

But which one you should use depends on what you want to do with it :)
