### ISSUE TITLE
Having the shared media available as new users enter room 

### ISSUE THREAD

**Issue by MORRA-RM** [miroslavpejic85/mirotalksfu#180]
### Feature request

Greetings. I was wondering if this is possible. When I share a media URL its visible to everyone in the room. However if a new person enters I they cant see it. I usually just reload the URL. 

### Pros

This would alleviate having to cancel and reshare the media. Hope you are doing good. Thanks again and keep up the great work. You are making the world a better place. 💜

### Additional context

this is my info
{
  "browser": {
    "name": "chrome",
    "version": "130.0.0.0",
    "major": "130"
  },
  "cpu": {},
  "device": {
    "vendor": "Apple",
    "model": "macintosh"
  },
  "engine": {
    "name": "Blink",
    "version": "130.0.0.0"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  }
}

**Comment by miroslavpejic85** [comment]
> This would alleviate having to cancel and reshare the media. 

I'm agree ;)

> Hope you are doing good. Thanks again and keep up the great work. You are making the world a better place. 💜

Thank you so much for your kind words! 😊 It truly means a lot to know that I can make a positive difference. It’s always a pleasure to help.

Work in progress.... Comming soon.

**Comment by miroslavpejic85** [comment]
![mirotalk-sfu-share-media](https://github.com/user-attachments/assets/e071fd34-7478-4683-9311-9c52d2c97818)

**Comment by MORRA-RM** [comment]
YYYYEEEESSSSS!!!!!!  I wish you could hear me yelling in happiness. thank you so much
