### ISSUE TITLE
Question: how to change default room settings, especially enabling the lobby?

### ISSUE THREAD

**Issue by avatar1024** [miroslavpejic85/mirotalksfu#181]
### Describe the bug

Hello,

Sorry I cannot access the Discord community forum to ask this.

I would like for the lobby to be enabled by default on room creation. Is it possible to specify default room settings inthe config.js file. I looked at the template but could not work it out.

Many thanks

Gauthier

### Steps to reproduce

Creat a new a room

### Expected behavior

Lobby is on

### Device

- [ ] Android
- [ ] iPhone
- [ ] Linux
- [ ] Mac
- [ ] Windows

### Browser

- [ ] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Android browser
- [ ] iOS browser
- [ ] Other desktop browser

### Reproducibility

Yes

**Comment by miroslavpejic85** [comment]
> Sorry I cannot access the Discord community forum to ask this.

Please avoid using GitHub for `questions`. If you're unable to access Discord, consider using a VPN.

![mirotalk-sfu-lobby](https://github.com/user-attachments/assets/57c875b4-ebc9-4939-bb0d-50d4b70af985)

In the `settings`, the `active lobby` feature will be retained for future sessions and rooms. 

And just a reminder, this definitely doesn’t belong in the bug section! 😉

Cheers!
