### ISSUE TITLE
When I play a video from track upload and start recording, only my own voice is saved in the screen recording. I also need the audio from the track upload music to be recorded.

### ISSUE THREAD

**Issue by MuhammadUsmanAnsari** [miroslavpejic85/mirotalksfu#182]
### Feature request

...

### Pros

...

**Comment by miroslavpejic85** [comment]
Please avoid detailing `everything in the title section`, as there’s a designated form for that purpose!

For `ideas and suggestions`, please use our dedicated forum: https://discord.com/invite/rgGYfeYW3N

Thank you!
