### ISSUE TITLE
Layout when someone sharing screen

### ISSUE THREAD

**Issue by edric4github** [miroslavpejic85/mirotalksfu#183]
### Feature request

i notice that the layout of video call show equal division between participant even when someone started to share screen. this mean that if someone is presenting a slideshow on thier screen, the rest of the participant will see a rather small screen of that shared screen. 

this largely reduce mirotalk usability for video conference involving presentation which is one of the most common use case.

i suggest if 1 person share screen, the screen will take up the whole screen, while the presenter webcam show up on the right lower corner as a mini floating video.  if someone else speaks, then a second/third mini floating video appear

### Pros

better visibility of the share screen presentation. 

focused on the speaker +/- the person asking question

**Comment by miroslavpejic85** [comment]
Hi @edric4github,

You can already use the `Focus Mode` feature! :)

The focus mode is designed to help you concentrate on a specific participant by hiding all others and bringing the selected person to full-screen size. This is particularly useful when you want to focus on someone who is sharing their screen or delivering a presentation, as it minimizes distractions from other participants in the meeting or if you want to highlight the presenter.

![mirotalk-sfu-focus-mode](https://github.com/user-attachments/assets/a59fee28-79f1-49ae-9cda-e8114dcb105c)

Pros of Focus Mode:
- **Enhanced Engagement**: By placing the selected participant in full-screen, you can give them your undivided attention, which is helpful during important discussions or presentations.
- **Reduced Distractions**: This feature hides all other participants temporarily, creating a cleaner, more focused view.
- **Screen Sharing Optimization**: If someone is sharing their screen, you can use focus mode to view their content more clearly and without interference from other thumbnails or video feeds.
- **Improved Visual Clarity**: In larger meetings, focus mode allows you to single out key participants, making it easier to track the conversation or presentation.

**Comment by edric4github** [comment]
thank you for your explanation. i will test it now. and i want to thank you for making such a useful piece of software. Bravo

**Comment by edric4github** [comment]
> Hi @edric4github,
> 
> You can already use the `Focus Mode` feature! :)
> 
> The focus mode is designed to help you concentrate on a specific participant by hiding all others and bringing the selected person to full-screen size. This is particularly useful when you want to focus on someone who is sharing their screen or delivering a presentation, as it minimizes distractions from other participants in the meeting or if you want to highlight the presenter.
> 
> ![mirotalk-sfu-focus-mode](https://private-user-images.githubusercontent.com/70838434/389703267-a59fee28-79f1-49ae-9cda-e8114dcb105c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDY5NjgsIm5iZiI6MTczMzcwNjY2OCwicGF0aCI6Ii83MDgzODQzNC8zODk3MDMyNjctYTU5ZmVlMjgtNzlmMS00OWFlLTljZGEtZTgxMTRkY2IxMDVjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAxMTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZTRjOTc1ZTMwMzQ5NzJkMWY3ODA1YjUzZjhkYjA5ZWU0ZTNlZWE0MTRiNDBlODQ1YzU0MTZhZDlhNGFkZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0hqipWnWPkTDjsxu5uT5_wqYjfnkiu09xqihVp7vvqM) [ ![mirotalk-sfu-focus-mode](https://private-user-images.githubusercontent.com/70838434/389703267-a59fee28-79f1-49ae-9cda-e8114dcb105c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDY5NjgsIm5iZiI6MTczMzcwNjY2OCwicGF0aCI6Ii83MDgzODQzNC8zODk3MDMyNjctYTU5ZmVlMjgtNzlmMS00OWFlLTljZGEtZTgxMTRkY2IxMDVjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAxMTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZTRjOTc1ZTMwMzQ5NzJkMWY3ODA1YjUzZjhkYjA5ZWU0ZTNlZWE0MTRiNDBlODQ1YzU0MTZhZDlhNGFkZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0hqipWnWPkTDjsxu5uT5_wqYjfnkiu09xqihVp7vvqM) ](https://private-user-images.githubusercontent.com/70838434/389703267-a59fee28-79f1-49ae-9cda-e8114dcb105c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDY5NjgsIm5iZiI6MTczMzcwNjY2OCwicGF0aCI6Ii83MDgzODQzNC8zODk3MDMyNjctYTU5ZmVlMjgtNzlmMS00OWFlLTljZGEtZTgxMTRkY2IxMDVjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAxMTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZTRjOTc1ZTMwMzQ5NzJkMWY3ODA1YjUzZjhkYjA5ZWU0ZTNlZWE0MTRiNDBlODQ1YzU0MTZhZDlhNGFkZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0hqipWnWPkTDjsxu5uT5_wqYjfnkiu09xqihVp7vvqM) [ ](https://private-user-images.githubusercontent.com/70838434/389703267-a59fee28-79f1-49ae-9cda-e8114dcb105c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDY5NjgsIm5iZiI6MTczMzcwNjY2OCwicGF0aCI6Ii83MDgzODQzNC8zODk3MDMyNjctYTU5ZmVlMjgtNzlmMS00OWFlLTljZGEtZTgxMTRkY2IxMDVjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAxMTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZTRjOTc1ZTMwMzQ5NzJkMWY3ODA1YjUzZjhkYjA5ZWU0ZTNlZWE0MTRiNDBlODQ1YzU0MTZhZDlhNGFkZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0hqipWnWPkTDjsxu5uT5_wqYjfnkiu09xqihVp7vvqM)
> 
> Pros of Focus Mode:
> 
>     * **Enhanced Engagement**: By placing the selected participant in full-screen, you can give them your undivided attention, which is helpful during important discussions or presentations.
> 
>     * **Reduced Distractions**: This feature hides all other participants temporarily, creating a cleaner, more focused view.
> 
>     * **Screen Sharing Optimization**: If someone is sharing their screen, you can use focus mode to view their content more clearly and without interference from other thumbnails or video feeds.
> 
>     * **Improved Visual Clarity**: In larger meetings, focus mode allows you to single out key participants, making it easier to track the conversation or presentation.

i noticed this feature is absent in the mobile mode. at least when i tested it on your demo site. also, in mobile mode, i notice there is no screensharing option, is it a limitation an mobile browser?
