### ISSUE TITLE
host.protected. Guest Login from "whoAreYou" not possible when host joins room delayed.

### ISSUE THREAD

**Issue by mz05er** [miroslavpejic85/mirotalksfu#187]
### Describe the bug
Settings from config.js are:

```
    host: {
        /*
            Host Protection (default: false)
            To enhance host security, enable host protection - user auth and provide valid
            usernames and passwords in the users array or active users_from_db using users_api_endpoint for check.
            When oidc.enabled is utilized alongside host protection, the authenticated user will be recognized as valid.
        */
        protected: true,
        user_auth: false,
        users_from_db: false, // if true ensure that api.token is also set to true.
        users_api_endpoint: 'http://localhost:9000/api/v1/user/isAuth',
        users_api_room_allowed: 'http://localhost:9000/api/v1/user/isRoomAllowed',
        users_api_rooms_allowed: 'http://localhost:9000/api/v1/user/roomsAllowed',
        api_room_exists: 'http://localhost:9000/api/v1/room/exists',

```
When guest try to join a room but the room is not initialized yet by host, the guest will see 
<img width="531" alt="Bildschirmfoto 2024-12-10 um 07 22 58" src="https://github.com/user-attachments/assets/f9c7326b-2e32-4093-9015-4d019af73650">

When the host initialize the room the above will change to
<img width="531" alt="Bildschirmfoto 2024-12-10 um 07 26 00" src="https://github.com/user-attachments/assets/0afb38f9-d550-4c2a-9e09-3cbda3b6fcdb">

By clicking the "Join Room" button, nothing happens.

A room for host is created by using e.g. :
```
curl -X POST "https://sfu.mirotalk.com/api/v1/join" \
-H "authorization: mirotalksfu_default_secret" \
-H "Content-Type: application/json" \
--data '{"room":"MyNewRoom","name":"presenter","audio":"true","video":"true","screen":"false","hide":"false","notify":"true","token":{"username":"username","password":"password","presenter":"true", "expire":"1d"}}
```
The client URL to join is :
https://sfu.mirotalk.com/join?room=MyNewRoom

P.S: i added sfu.mirotalk.com as placeholder

### Steps to reproduce

1. create room with curl
2. try to enter the room as client first
3. enter the room as host
4. for the client the "whoAreYou" buttons are changing to "Join Room" only. Connecting to the room by clicking is not possible 

### Expected behavior

When for the client the  "whoAreYou" buttons are changing to "Join Room" only, client should ba able to connect to the room and see
<img width="994" alt="Bildschirmfoto 2024-12-10 um 07 50 20" src="https://github.com/user-attachments/assets/7c6bb6bf-7a7b-44d8-b52d-752b797426ce">

### Device

- [ ] Android
- [ ] iPhone
- [ ] Linux
- [X] Mac
- [X] Windows

### Browser

- [X] Chrome (or Chromium based)
- [X] Firefox
- [X] Safari
- [ ] Android browser
- [ ] iOS browser
- [ ] Other desktop browser

### Reproducibility

No

### Additional context

Thank's for your work and great app !!

**Comment by miroslavpejic85** [comment]
This is exactly the level of detail I hope to see when someone submits a bug report. Great job!

Will be fixed ASAP.

> Thank's for your work and great app !!

You're welcome! 😊 

Thank you for your kind words. 

I'm so glad you're enjoying the app! 🚀

**Comment by mz05er** [comment]
Wow, that was super fast !!
I can confirm it is working. :thumbsup: :clap:
Thank you very much.

**Comment by avatar1024** [comment]
@mz05er Sorry for a probably stupid question, but how can I reproduce the behaviour showed in the OP so that when guest show up they are presented with this 

![Image](https://github.com/user-attachments/assets/3641e832-4249-47ba-b58b-6ec41b8c5cd7)

instead of just a login screen?

PS: I have OIDC connect enabled

**Comment by miroslavpejic85** [comment]
> PS: I have OIDC connect enabled

The `Who Are You` page feature is currently only available when using `HOST_PROTECTED` mode. For now It is `not supported` with `OIDC authentication`.
