### ISSUE TITLE
Meeting stops working after a minute or so

### ISSUE THREAD

**Issue by jhjacobs81** [miroslavpejic85/mirotalksfu#19]
![image](https://user-images.githubusercontent.com/5583803/136599332-b5d99e31-dcae-4a02-b953-e254eee036f0.png)

It freezeslike this screen

**Comment by miroslavpejic85** [comment]
Hi, `meet.canandoyle.eu` seem not my demo.
Do you have the same problem here: https://sfu.mirotalk.org ?
If yes, past me here the browser console error log if there is.
Thanks
