### ISSUE TITLE
Feature request: some form of authentication

### ISSUE THREAD

**Issue by jhjacobs81** [miroslavpejic85/mirotalksfu#20]
some form of authentication would be nice. In my case i would like to limit the creation of meetings to authenticated users, but allow guest users to join meetings when approved by the meeting owner

**Comment by miroslavpejic85** [comment]
Hello, you can also found some response on closed issue :)
Regarding your question: https://github.com/miroslavpejic85/mirotalksfu/issues/13#issuecomment-932416012

**Comment by miroslavpejic85** [comment]
For custom uses, you can adapt the code... :)
