### ISSUE TITLE
WebSocket Connection Error

### ISSUE THREAD

**Issue by aikozijlemans** [miroslavpejic85/mirotalksfu#23]
### socket.io.js:324 WebSocket connection to 'wss://chat.fyi411.net/socket.io/?EIO=4&transport=websocket&sid=4yYRMwDmDxBEw57XAAAG' failed: 

people can join but not be able to talk to one another or stream camera

**Comment by Jaideep25** [comment]
Hello @aikozijlemans !
Could you please text, if you got this error in https://sfu.mirotalk.org or while using your client?
Thanks!

**Comment by aikozijlemans** [comment]
I only get it on my end.

**Comment by Jaideep25** [comment]
Okay cool, you have not portforwarded, please do follow these steps : 

> On config.js change this and then rebuild the image:
> 
> ```js
> announcedIp: YOUR-PUBLIC-STATIC-IP-HERE, // replace by public static IP address https://api.ipify.org
> ```
> 
> Then port-forwarding something like this on `router` settings:
> 
> Name	Protocol	Port Wan	Port Lan	IP Destination
> `MiroTalkSfu`	`TCP/UDP`	40000:40100	40000:40100	`Your Local IP`
> `MiroTalkSfu `	`TCP/UDP`	3010	3010	`Your Local IP`
> Make sure your firewall not blocking rtcPorts range : `40000:40100`
> 
> Tested and works:
> 
> * Mac BigSur 11.6 (20G165)
> * Firefox 92.0.1 (64bit)
> 
> Regards

**Comment by aikozijlemans** [comment]
how do i do this to be exact because it shows me 

```

npm ERR! Failed at the mirotalksfu@1.0.0 start script.


npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:


npm ERR!     /root/.npm/_logs/2021-10-31T01_35_51_512Z-debug.log



> mirotalksfu@1.0.0 start /src


> node app/src/Server.js



/src/app/src/config.js:102


                    announcedIp: 88.888.88.88, // fake ip for reasons


                                      ^^^^



SyntaxError: Unexpected number


    at wrapSafe (internal/modules/cjs/loader.js:1001:16)


    at Module._compile (internal/modules/cjs/loader.js:1049:27)


    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)


    at Module.load (internal/modules/cjs/loader.js:950:32)


    at Function.Module._load (internal/modules/cjs/loader.js:790:12)


    at Module.require (internal/modules/cjs/loader.js:974:19)


    at require (internal/modules/cjs/helpers.js:93:18)


    at Object.<anonymous> (/src/app/src/Server.js:8:16)


    at Module._compile (internal/modules/cjs/loader.js:1085:14)


    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)


npm ERR! code ELIFECYCLE


npm ERR! errno 1


npm ERR! mirotalksfu@1.0.0 start: `node app/src/Server.js`


npm ERR! Exit status 1
```

**Comment by Jaideep25** [comment]
Oh, you're in windows OS or Mac OS or Fedora?

**Comment by aikozijlemans** [comment]
No I am using docker on Ubuntu 21.10

**Comment by aikozijlemans** [comment]
its a server specifically

**Comment by Jaideep25** [comment]
Okay, try port forwarding, and do check this out if you followed all these steps : 
![image](https://user-images.githubusercontent.com/67269475/139563331-c451c9d2-2e74-45f8-9730-b505d82d8193.png)

Cuz the mic and cam prob is of only n only portforwarding or wrong config (happened to me too)

**Comment by aikozijlemans** [comment]
it installed before perfectly fine, node.js is installed because i run most stuff on node.js

it only happened after i changed this

```
webRtcTransport: {
            listenIps: [
                {
                    ip: '0.0.0.0',
                    announcedIp: getLocalIp(), // replace by public static IP address https://api.ipify.org
                },
            ],
            maxIncomingBitrate: 1500000,
            initialAvailableOutgoingBitrate: 1000000,
        },
        ```

to this 

```
webRtcTransport: {
            listenIps: [
                {
                    ip: '0.0.0.0',
                    announcedIp: 88.88.888.8, // specifically this line and it throws a error here
                },
            ],
            maxIncomingBitrate: 1500000,
            initialAvailableOutgoingBitrate: 1000000,
        },
    },
```

**Comment by aikozijlemans** [comment]
SyntaxError: Unexpected number on the announcedIp

**Comment by Jaideep25** [comment]
Oh don't change that, line, if you change that function won't be called, please port forward and then try if those errors still persist!

**Comment by aikozijlemans** [comment]
i already tried that and port forward it then i get 

### socket.io.js:324 WebSocket connection to 'wss://chat.fyi411.net/socket.io/?EIO=4&transport=websocket&sid=4yYRMwDmDxBEw57XAAAG' failed:

**Comment by Jaideep25** [comment]
Hmm, what error comes in your logs? And if possible could you show your npm, node and python versions. Even check out if you have run build essential cmd!

**Comment by Jaideep25** [comment]
Hey @aikozijlemans , i guess the problem is maybe with your Ubuntu version, cuz of the latest version see the latest commits!
![image](https://user-images.githubusercontent.com/67269475/139571064-17f8a20c-cf3b-4f04-aa58-a61b718b25dc.png)

https://github.com/miroslavpejic85/mirotalksfu/commit/2a7f96ed295938b6d5878467437a513fcd8b97f5

**Comment by miroslavpejic85** [comment]
@Jaideep25 thanks, It's true that it has to do port forwarding to make it work outside the LAN. Also specified [here](https://github.com/miroslavpejic85/mirotalksfu/issues/11#issuecomment-927353690)

@aikozijlemans But what I see in your logs, the message is clear 

```bash
SyntaxError: Unexpected number on the announcedIp
```

So `change` 88.88.888.8 with '88.88.888.8', you're missing the `'`  :)

Regards
