### ISSUE TITLE
Password for joining room

### ISSUE THREAD

**Issue by Sanyam2007** [miroslavpejic85/mirotalksfu#24]
Hi Miroslavpejic85
I just want you to add a feature for password before entering the
Room as once someone locked the room and started meeting
He has to unlock again for late people to join so in this view password authentication is good.

**Comment by miroslavpejic85** [comment]
Hello @Sanyam2007,
Aha, in addition to the function to lock the room that already implemented, possibility to protect the room with a password once inside so that if one wants to enter it must enter the correct password, right?

**Comment by Sanyam2007** [comment]
Yes,if someone wants to enter he will enter the correct password set by the creator of the room and can join easily
People in the meeting than don't have to lock and unlock room again and again.

**Comment by miroslavpejic85** [comment]
done: https://github.com/miroslavpejic85/mirotalksfu/commit/e055d2128b19b1c82e22cfee586fcea18e1d3fe3
