### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by OrionRandD** [miroslavpejic85/mirotalksfu#26]
For Teaching purposes, do you think the Demo version is enough?
Or should I install it locally…

**Comment by miroslavpejic85** [comment]
Hello @OrionRandD, thanks for trying MiroTalk. Let's say the intention of the Demo is to give everyone a chance to see how it works :) It would be better to create your own personal droplet instance on [DigitalOcean](https://m.do.co/c/1070207afbb1), In order to have this service all Yours, and not depend on the Demo ;) For any doubts or questions you can also contact me directly at: miroslav.pejic.85@gmail.com
Many Thanks

**Comment by OrionRandD** [comment]
> Hello @OrionRandD, thanks for trying MiroTalk. Let's say the intention of the Demo is to give everyone a chance to see how it works :) It would be better to create your own personal droplet instance on [DigitalOcean](https://m.do.co/c/1070207afbb1), In order to have this service all Yours, and not depend on the Demo ;) For any doubts or questions you can also contact me directly at: [miroslav.pejic.85@gmail.com](mailto:miroslav.pejic.85@gmail.com) Many Thanks

I have installed the server in my notebook. It seems to work, but I got a warnings message complaining that my "/usr/bin/uuid"  is an older version  it  3x...   But, I checked my npm, and it is above npm -version 7.20.3
Seems that it is ok...
I deleted the uuid and reinstalled again, deleted the local repo, cloned again, installed again and  it still complained about it. I got there hangled. Then I issued C-c and did "npm start" and got the local url and that worked. But, I think that although it says https, it is not encrypted locally... I think it is useful... probably...

**Comment by miroslavpejic85** [comment]
Thanks for the update, 

If you want to expose it from your Local PC to outside in HTTPS, you need to do 2 things:

1) Add ngrok [authToken](https://github.com/miroslavpejic85/mirotalksfu/blob/main/app/src/config.template.js#L32) and change the [announcedIp](https://github.com/miroslavpejic85/mirotalksfu/blob/main/app/src/config.template.js#L102)

 - In `app/src/` copy config.template.js to `config.js` then

```js
    /*
    Ngrok
        1. Goto https://ngrok.com
        2. Get started for free
        3. Copy YourNgrokAuthToken: https://dashboard.ngrok.com/get-started/your-authtoken
    */

    ngrokAuthToken: 'YourNgrokAuthToken', <--- put it here

    announcedIp: 'Your-Public-Static-IP-here' <--- take it from https://api.ipify.org
```

2) You need to do a port forwarding on your router, something like this:

|  Name               |  Protocol      | Port Wan          | Port Lan         |  IP Destination      |
|----------------|-------------|----------------|--------------|------------------|
| `MiroTalkSfu`   | `TCP/UDP`  | 40000:40100  | 40000:40100 | `Your Local IP`   |
| `MiroTalkSfu`   | `TCP/UDP`  | 3010                 | 3010                | `Your Local IP`   |

Make sure your firewall not blocking rtcPorts `range: 40000:40100`

Then, when you run it with `npm start`, you should see in the console log this line:

```bash
tunnel: 'https://xxxxxxxxxxxxxxxxxx.ngrok.io'
```

So open it in your browser, join in your room, share it to whom you want and wait participants to join ;)

Regards

**Comment by OrionRandD** [comment]
Thx alot for the help. 
I will tell other people about your app...

**Comment by miroslavpejic85** [comment]
You are welcome, thank you very much.
