### ISSUE TITLE
[BUG] Full screen does not work reliably

### ISSUE THREAD

**Issue by nikoksr** [miroslavpejic85/mirotalksfu#29]
**Describe the bug**

Fullscreen mode toggling for user screens not working realiably.

**To Reproduce**

1. Start a new session
2. Invite a friend
3. Share your screen
4. Let your friend click on your screen in order to 'maximize' the view
5. Let your friend exit the fullscreen mode
6. Now your friend should not be able to maximize the view again unless he rejoins the session

**Expected behavior**

Being able to consistently toggle between fullscreen and normal mode.

**System**

 - Browser: Firefox Developer Edition 96.0b4 (64-bit)
 - OS: Arch Linux 
 - Kernel: 5.15.7-zen1-1-zen
 - Protocol: Wayland

**Additional context**

Bug occured when using the provided demo under [sfu.mirotalk.org](https://sfu.mirotalk.org). I did not test it when self-hosted.

**Comment by nikoksr** [comment]
Glanced over the code and potentially found the bug. I think your check for fullscreen [here](https://github.com/miroslavpejic85/mirotalksfu/blob/d04294133a258bbe140158d1936d1428e47f00c4/public/js/RoomClient.js#L1341) fails. After exiting fullscreen for the first time the check stays `true` even though it should be `false`.

Screenshot of `document.fullscreenEnabled`'s value after entering and exiting fullscreen mode once:

![image](https://user-images.githubusercontent.com/31685472/146048272-42de3c98-cd4a-4efb-8f84-bad1dfaec8d3.png)

**Comment by miroslavpejic85** [comment]
Hello @nikoksr, 
You're right, the small bug is for all browser when press ESC to exit from full screen mode :) Will be fixed asap. Thanks

**Comment by miroslavpejic85** [comment]
Fixed on fly: https://github.com/miroslavpejic85/mirotalksfu/commit/8502ef3f8cc13d44087b32ff42762a95432ea650
