### ISSUE TITLE
Error when installing using npm

### ISSUE THREAD

**Issue by geekedtv** [miroslavpejic85/mirotalksfu#3]
Excuse my ignorance but this is my first time using npm but I am getting this error.

https://snip.lol/WeXO3/gUzEmeGA28.png

**Comment by miroslavpejic85** [comment]
Hi @geekedtv,
Following [this](https://github.com/miroslavpejic85/mirotalksfu#quick-start)
Are you missing ? :)
```bash
cp src/config.template.js src/config.js
```

**Comment by geekedtv** [comment]
Ah yes, I forgot to copy over the config. derp lol. thanks!
