### ISSUE TITLE
How to host it on netlify railway or heroku 

### ISSUE THREAD

**Issue by Sanyam2007** [miroslavpejic85/mirotalksfu#32]
Please tell the steps to host it on railway heroku or netlify please!

**Comment by miroslavpejic85** [comment]
Hello @Sanyam2007, It is not possible, you can deploy it on [DigitalOcean](https://m.do.co/c/1070207afbb1), Aws-ec2 or on your own dedicated server (self-hosted). Or alternatively, if you want to try it from your Local PC, [check this out](https://github.com/miroslavpejic85/mirotalksfu/issues/26#issuecomment-986309051).  Regards
