### ISSUE TITLE
Record participants audio

### ISSUE THREAD

**Issue by bloodyburger** [miroslavpejic85/mirotalksfu#33]
The recording feature works by recording presenters video/audio, good to record all participants audio to have a complete recording feature.

**Comment by miroslavpejic85** [comment]
check it out: https://github.com/muaz-khan/RecordRTC/wiki/Record-Multiple-Streams-Into-Single-File

**Comment by Owned-by-Luce** [comment]
I hope you will implement this soon.

**Comment by miroslavpejic85** [comment]
Useful links:

## Useful links:

- https://github.com/streamproc/MediaStreamRecorder
- https://www.webrtc-experiment.com/msr/MultiStreamRecorder.html
- https://github.com/streamproc/MediaStreamRecorder/blob/master/demos/MultiStreamRecorder.html
