### ISSUE TITLE
Bug report - able to create room without using authentication step

### ISSUE THREAD

**Issue by pomtom44** [miroslavpejic85/mirotalksfu#35]
Hi there

I have a server iv been setting up, i have the authentication enabled so only I can create rooms which works fine
however iv noted if you go to /join/anynamehere it will create a room with that name without the user having to authenticate

not sure if its just an issue with my install, or a bug in the code

**Comment by miroslavpejic85** [comment]
Hello @pomtom44, I think it's my oversight, I tagged it as a bug. Thank you.

**Comment by pomtom44** [comment]
Edit to bug
I can see now it asks you to authenticate, must have been fixed recently
However after a meeting it takes you to /newroom where any user can create a room
Had a look at the code and I can see the authentication, but I assume all the users are being marked as authenticated after the meeting so can access the /newroom page?

**Comment by miroslavpejic85** [comment]
Hello @pomtom44, 
Are you aligned with the MiroTalk master branch?, currently when a user leaves the room they should be redirected to the [survey page](https://www.questionpro.com/t/AUs7VZq02P) recently implemented to collect some useful data to improve the MiroTalk service.

**Comment by miroslavpejic85** [comment]
done: https://github.com/miroslavpejic85/mirotalksfu/commit/f45d41a5e9a39da241be3c25fe85ac288980b300
