### ISSUE TITLE
help me install on MacOS for testing

### ISSUE THREAD

**Issue by ihubgit** [miroslavpejic85/mirotalksfu#36]
Hi, tried several times to install, but as i'm not a *nix geek, got it wrong every time.
Trying to follow instructions on your link (mediasoup).
This is what i did so far :
https://mediasoup.org/documentation/v3/mediasoup/installation/#requirements
```bash
All platforms
    node version >= v12.0.0
    python version >= 3.6 with PIP
    GNU make
Linux, OSX and any *NIX system
    gcc and g++ >= 4.9 or clang (with C++11 support)
    cc and c++ commands (symlinks) pointing to the corresponding gcc/g++ or clang/clang++ executables.
```
1 installed NodeJs 16.13.2
2 installed python 3.10.2
3 installed PIP with command curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
4 already have clang 12.0.5 installed
- so, what's this GNU make? Can't find any information on Google
- lost for the cc and cc++ commands

Thanks for helping me out with these last two steps.
Once i get those ok, i follow the following instructions?

# Clone this repo
```bash
 git clone https://github.com/miroslavpejic85/mirotalksfu.git
 # Go to to dir mirotalksfu
 cd mirotalksfu
 # Copy app/src/config.template.js in app/src/config.js and edit it if needed
 cp app/src/config.template.js app/src/config.js
 # Install dependencies
 npm install
 # Start the server
 npm start
 ```

**Comment by ihubgit** [comment]
Hi, so just did the last steps (clone this repo).
This is the output for the 'npm cmd' :
> poste@macbook ~ % git clone https://github.com/miroslavpejic85/mirotalksfu.git
Clonage dans 'mirotalksfu'...
remote: Enumerating objects: 1331, done.
remote: Counting objects: 100% (501/501), done.
remote: Compressing objects: 100% (172/172), done.
remote: Total 1331 (delta 407), reused 399 (delta 329), pack-reused 830
Réception d'objets: 100% (1331/1331), 2.13 Mio | 1.55 Mio/s, fait.
Résolution des deltas: 100% (878/878), fait.
poste@macbook ~ % cd mirotalksfu
poste@macbook mirotalksfu % cp app/src/config.template.js app/src/config.js
poste@macbook mirotalksfu % npm install
npm notice 
npm notice New minor version of npm available! 8.1.2 -> 8.3.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.3.2
npm notice Run npm install -g npm@8.3.2 to update!
npm notice 
npm ERR! code 1
npm ERR! path /Users/poste/mirotalksfu/node_modules/mediasoup
npm ERR! command failed
npm ERR! command sh -c node npm-scripts.js postinstall
npm ERR! npm-scripts.js [INFO] running task "postinstall"
npm ERR! npm-scripts.js [INFO] executing command: node npm-scripts.js worker:build
npm ERR! npm-scripts.js [INFO] running task "worker:build"
npm ERR! npm-scripts.js [INFO] executing command: make -C worker
npm ERR! # Updated pip and setuptools are needed for meson
npm ERR! # `--system` is not present everywhere and is only needed as workaround for
npm ERR! # Debian-specific issue (copied from
npm ERR! # https://github.com/gluster/gstatus/pull/33), fallback to command without
npm ERR! # `--system` if the first one fails.
npm ERR! /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -m pip install --system --target=/Users/poste/mirotalksfu/node_modules/mediasoup/worker/out/pip pip setuptools || \
npm ERR! 		/Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -m pip install --target=/Users/poste/mirotalksfu/node_modules/mediasoup/worker/out/pip pip setuptools || \
npm ERR! 		echo "Installation failed, likely because PIP is unavailable, if you are on Debian/Ubuntu or derivative please install the python3-pip package"
npm ERR! Collecting pip
npm ERR!   Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
npm ERR! Collecting setuptools
npm ERR!   Downloading setuptools-60.5.0-py3-none-any.whl (958 kB)
npm ERR! Installing collected packages: setuptools, pip
npm ERR! Successfully installed pip-21.3.1 setuptools-60.5.0
npm ERR! # Install `meson` and `ninja` using `pip` into custom location, so we don't
npm ERR! # depend on system-wide installation.
npm ERR! /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -m pip install --upgrade --target=/Users/poste/mirotalksfu/node_modules/mediasoup/worker/out/pip  meson ninja
npm ERR! Collecting meson
npm ERR!   Downloading meson-0.61.1-py3-none-any.whl (850 kB)
npm ERR! Collecting ninja
npm ERR!   Downloading ninja-1.10.2.3-py2.py3-none-macosx_10_9_universal2.macosx_10_9_x86_64.macosx_11_0_arm64.macosx_11_0_universal2.whl (231 kB)
npm ERR! Installing collected packages: ninja, meson
npm ERR! Successfully installed meson-0.61.1 ninja-1.10.2.3
npm ERR! /Users/poste/mirotalksfu/node_modules/mediasoup/worker/out/pip/bin/meson setup \
npm ERR! 		--prefix /Users/poste/mirotalksfu/node_modules/mediasoup/worker/out/Release \
npm ERR! 		--bindir '' \
npm ERR! 		--libdir '' \
npm ERR! 		--buildtype release \
npm ERR! 		-Db_ndebug=true \
npm ERR! 		-Db_pie=true \
npm ERR! 		-Db_staticpic=true \
npm ERR! 		--reconfigure \
npm ERR! 		"" \
npm ERR! 		/Users/poste/mirotalksfu/node_modules/mediasoup/worker/out/Release/build || \
npm ERR! 		/Users/poste/mirotalksfu/node_modules/mediasoup/worker/out/pip/bin/meson setup \
npm ERR! 			--prefix /Users/poste/mirotalksfu/node_modules/mediasoup/worker/out/Release \
npm ERR! 			--bindir '' \
npm ERR! 			--libdir '' \
npm ERR! 			--buildtype release \
npm ERR! 			-Db_ndebug=true \
npm ERR! 			-Db_pie=true \
npm ERR! 			-Db_staticpic=true \
npm ERR! 			"" \
npm ERR! 			/Users/poste/mirotalksfu/node_modules/mediasoup/worker/out/Release/build
npm ERR! The Meson build system
npm ERR! Version: 0.61.1
npm ERR! Source dir: /Users/poste/mirotalksfu/node_modules/mediasoup/worker
npm ERR! Build dir: /Users/poste/mirotalksfu/node_modules/mediasoup/worker/out/Release/build
npm ERR! Build type: native build
npm ERR! Project name: mediasoup-worker
npm ERR! Project version: undefined
npm ERR! C compiler for the host machine: cc (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.11)")
npm ERR! C linker for the host machine: cc ld64 650.9
npm ERR! C++ compiler for the host machine: c++ (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.11)")
npm ERR! C++ linker for the host machine: c++ ld64 650.9
npm ERR! Host machine cpu family: x86_64
npm ERR! Host machine cpu: x86_64
npm ERR! Downloading openssl source from https://www.openssl.org/source/openssl-1.1.1l.tar.gz
npm ERR! <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
npm ERR! A fallback URL could be specified using source_fallback_url key in the wrap file
npm ERR! 
npm ERR! meson.build:147:0: ERROR: could not get https://www.openssl.org/source/openssl-1.1.1l.tar.gz is the internet available?
npm ERR! 
npm ERR! A full log can be found at /Users/poste/mirotalksfu/node_modules/mediasoup/worker/out/Release/build/meson-logs/meson-log.txt
npm ERR! Usage:   
npm ERR!   /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -m pip install [options] <requirement specifier> [package-index-options] ...
npm ERR!   /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -m pip install [options] -r <requirements file> [package-index-options] ...
npm ERR!   /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -m pip install [options] [-e] <vcs project url> ...
npm ERR!   /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -m pip install [options] [-e] <local project path> ...
npm ERR!   /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -m pip install [options] <archive url/path> ...
npm ERR! 
npm ERR! no such option: --system
npm ERR! WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
npm ERR! You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -m pip install --upgrade pip' command.
npm ERR! Directory does not contain a valid build tree:
npm ERR! /Users/poste/mirotalksfu/node_modules/mediasoup/worker/out/Release/build
npm ERR! make: *** [setup] Error 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/poste/.npm/_logs/2022-01-26T07_42_25_031Z-debug.log
poste@macbook mirotalksfu % 

This is the output for the 'npm start cmd' :
> > mirotalksfu@1.0.0 start
> node app/src/Server.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /Users/poste/mirotalksfu/app/src/Server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/poste/mirotalksfu/app/src/Server.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/poste/mirotalksfu/app/src/Server.js' ]
}
npm notice 
npm notice New minor version of npm available! 8.1.2 -> 8.3.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.3.2
npm notice Run npm install -g npm@8.3.2 to update!
npm notice 
poste@macbook mirotalksfu % 

Can you please help me out sorting it out ? thanks !

**Comment by miroslavpejic85** [comment]
Hello @ihubgit, Are you Solved? I not tested it with nodejs 16 .. currently use NodeJS 14. Make sure you have installed all dependencies correctly following the errors log. You can also in case run it with [Docker](https://github.com/miroslavpejic85/mirotalksfu#docker). For mediasoup related issues you can also ask in the official forum [here](https://mediasoup.discourse.group/) concerning [deployment](https://mediasoup.discourse.group/c/deployment/). Thanks.

**Comment by Kareszrk** [comment]
same problem for me, but not on MacOS, I am using Ubuntu Server 22.04

**Comment by miroslavpejic85** [comment]
> same problem for me, but not on MacOS, I am using Ubuntu Server 22.04

Just follow this steps on how to self host it: https://github.com/miroslavpejic85/mirotalksfu/blob/main/docs/self-hosting.md
