### ISSUE TITLE
How best to update?

### ISSUE THREAD

**Issue by pomtom44** [miroslavpejic85/mirotalksfu#37]
Whats the best process to update?
Do I just download the git files again and re run the install command?
or is there another way?

**Comment by miroslavpejic85** [comment]
Hello @pomtom44,
It depends on how and where you have deployed it, one way could be this:

vim `updateMiroTalkSFU.sh`

```bash 
#!/bin/bash

cd mirotalksfu
git pull
docker-compose down
docker-compose build
docker images |grep '<none>' |awk '{print $3}' |xargs docker rmi
docker-compose up -d
```

Make it executable
```bash
chmod +x updateMiroTalkSFU.sh
```

Execute it when need
```bash
./updateMiroTalkSFU.sh
```

Regards
