### ISSUE TITLE
running mirotalk without ssl

### ISSUE THREAD

**Issue by jhjacobs81** [miroslavpejic85/mirotalksfu#38]
Hello!

I would like to run Mirotalk behind a proxy server, without SSL. i tried changing the Server.js file but then i get a bunch of errors i do not understand. is there a way to do so? I would like to use Caddy/Nginx as a reverse proxy server so we can use lets encrypt certificates instead of self signed. It also allows me to use a "normal url" instead of an url with :3010 behind

**Comment by miroslavpejic85** [comment]
Hello @jhjacobs81,
You not need to change anything on server.js, just edit `announcedIp` and put your public static IP on `config.js`
Setup and configuring Nginx on /etc/nginx/sites-enabled/default (configure the server name, domain, let's encrypt ssl certificate, http redirect to https and proxy all requests to the Node app http://localhost:3010/)
Check out also: https://certbot.eff.org/
Regards

**Comment by jhjacobs81** [comment]
You closed the issue, but unfortunatly it does not work :(

i setup caddy, it works. i can reverse_proxy apps, but with mirotalk it waits.. and waits.. and then times out. Docker says its running on port 3010.

**Comment by miroslavpejic85** [comment]
Also make sure the firewall doesn't block the rtc range ports...that is specified on config.js

**Comment by jhjacobs81** [comment]
i did it without docker, works almost perfectly :)
