### ISSUE TITLE
when will you realease bro

### ISSUE THREAD

**Issue by theprogrammingking** [miroslavpejic85/mirotalksfu#4]

**Comment by theprogrammingking** [comment]
when will you realease

**Comment by Jaideep25** [comment]
@theprogrammingking  what do you want @miroslavpejic85  to release?

**Comment by miroslavpejic85** [comment]
Currently, this version is deployed as a droplet in [DigitalOcean](https://m.do.co/c/1070207afbb1) for personal use - test, as the `service is paid`. 

![image](https://user-images.githubusercontent.com/70838434/131631389-c7a7d7ac-6b33-4969-80d1-ea376eb8e688.png)

To make it public I would have to upgrade the current VM which would require additional `maintenance costs`. 
Regards
