### ISSUE TITLE
Deployment on render.com

### ISSUE THREAD

**Issue by Julienng** [miroslavpejic85/mirotalksfu#40]
Hi, I've been attempting to deploy mirotalks SFU on render.com unsuccessfully.

I followed the instruction, the deployments works but, if I test it out, only the chat is working. I have a loading spinner on other participants.

Example :

![image](https://user-images.githubusercontent.com/8990614/156204413-3d1d22d4-ed79-4aed-950b-73554a9d8a83.png)

The URL of the tested service : https://visio.onrender.com/

Do you have any recommendation or advice to make it works?

Thank you

**Comment by miroslavpejic85** [comment]
Hello @Julienng, Thanks for trying MiroTalk.

In `app/src/config.js` make sure to have this settings:

```js
	ip: '0.0.0.0',
	announcedIp: '216.24.57.253', // replace by your public static IP address
```

And also make sure the `Firewall` not blocks the RTC port ranges: `40000:40100`
