### ISSUE TITLE
Replace Google Analytics

### ISSUE THREAD

**Issue by mawoka-myblock** [miroslavpejic85/mirotalksfu#42]
I think that it is self-explaining why Google Analytics is bad. On reddit, they are also talking about it: https://www.reddit.com/r/selfhosted/comments/tnh3gs/comment/i21jv4q

**Comment by miroslavpejic85** [comment]
Thank you so much for your suggestions, I'll take a look at them.

**Comment by miroslavpejic85** [comment]
I would say [umami](https://app.umami.is/share/8rmHaheU/umami.is) single page is perfect!

**Comment by mawoka-myblock** [comment]
> I would say [umami](https://app.umami.is/share/8rmHaheU/umami.is) single page is perfect!

That's a great decision!

**Comment by miroslavpejic85** [comment]
@mawoka-myblock, replaced: https://github.com/miroslavpejic85/mirotalksfu/commit/012acd562c69405051ec16b88f1d8c1235d5efc4
