### ISSUE TITLE
Whether mirotalk load balancing is possible.

### ISSUE THREAD

**Issue by chocopieban** [miroslavpejic85/mirotalksfu#43]
I wonder how many people can fit in one room at most.
If the capacity is small, the capacity should be increased through multiple servers.
Can you recommend the method?

**Comment by miroslavpejic85** [comment]
Hello @chocopieban,

MiroTalk uses a powerful integrated [mediasoup](https://mediasoup.org/).
So regarding your question you can find the answer here: https://mediasoup.org/documentation/v3/scalability/

For any questions or concerns, you can also subscribe to the [discourse group](https://mediasoup.discourse.group/) and find many answers to questions like this you asked me ;) 

Thanks for trying MiroTalk.
