### ISSUE TITLE
Precompiled Docker ? Precompiled Binaries for nondocker aswell???

### ISSUE THREAD

**Issue by Liyoshinka** [miroslavpejic85/mirotalksfu#44]
### Feature request

I would like to have binaries 
compiling the project is a nightmare. 2 hours I wont get

### Pros
I cannot ```npm i``` 
so fucking annoying I cant get the docker to work too :( 

The other mirotalk works fine but people in austrailia cant join my session the 
sfu.mirotalk.org suck so I am stuck

**Comment by Liyoshinka** [comment]
![image](https://user-images.githubusercontent.com/101117362/162199276-633f0c64-da9f-4279-858d-6d73dd2315eb.png)
stop the coompiling gentoo meme please!!!!!

**Comment by miroslavpejic85** [comment]
Hello @Liyoshinka,

The first installation can be slow (it have to install all dependencies etc.), the following ones if the package.json is not modified should be almost immediate.

I leave it to others to decide how to create-manage their own docker images. 
In alternative you can try also [PM2](https://pm2.keymetrics.io/docs/usage/process-management/)

And keep the project up to date with a script to run as needed:

```bash
#!/bin/bash

cd mirotalksfu
git pull
pm2 stop 0
sudo npm install
pm2 start 0
```
Thanks again for trying MiroTalk.
All the best!
