### ISSUE TITLE
bug found :- when we hit video button continuously

### ISSUE THREAD

**Issue by alimaqsood3** [miroslavpejic85/mirotalksfu#46]
Hi @miroslavpejic85  hope you are doing well. Thanks for the amazing solution sir,
So I was testing Mirotalk Sfu and when we hit the video button 5 to 6 times continuously then another video container opened in the same room automatically.
please check the attached video file for reference 

thanks :)

https://user-images.githubusercontent.com/44001150/163292713-b3cd4cc3-b9ed-4fc2-a072-9f1e7f92a933.mp4

**Comment by miroslavpejic85** [comment]
Hello @alimaqsood3,
Thank you very much, you are right, it will be fixed!

**Comment by miroslavpejic85** [comment]
@alimaqsood3 done: https://github.com/miroslavpejic85/mirotalksfu/commit/3021c06630ab0a6730f7d7187e36511890ae271b

**Comment by alimaqsood3** [comment]
thank you soo much Sir @miroslavpejic85

**Comment by miroslavpejic85** [comment]
done: https://github.com/miroslavpejic85/mirotalksfu/commit/ad7b11dba5a4cb0cb0af7cfd587354e9e01be9c8
