### ISSUE TITLE
double click on video container video 

### ISSUE THREAD

**Issue by alimaqsood3** [miroslavpejic85/mirotalksfu#47]
when we click on video container then video stuck or full screen opens  when we press `ESC` key to get back the video call the call stuck 
I did a simple solution may be can work 
`#videoMediaContainer video ` set property  `pointer-events: none !important;`

thanks

**Comment by miroslavpejic85** [comment]
Hi @alimaqsood3,

It is not clear to me what you meant, can you take me a video or a screenshot? 
Also specifying the device and browser.

Currently to set the video element to full screen just click on it, then click on it again or press ESC to exit full screen mode.

Thanks
