### ISSUE TITLE
Need ScreenShare with audio

### ISSUE THREAD

**Issue by chennasi** [miroslavpejic85/mirotalksfu#49]
### Feature request

A clear and concise description of the feature request.

Need ScreenShare with audio and add new blackbox for screenshare

**Comment by miroslavpejic85** [comment]
Hello @chennasi,
The audio capture with getDisplayMedia is not fully supported, It's not depend of MiroTalk but by the WebRTC Api it self, more details about browser compatibility you can read here: 
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia#browser_compatibility
If you want to try this functionality, just set the audio: true on [getScreenConstaints()](https://github.com/miroslavpejic85/mirotalksfu/blob/main/public/js/RoomClient.js#L740)
Regards.
