### ISSUE TITLE
iPhone doesn't see video spinning blue circle

### ISSUE THREAD

**Issue by ioscanner** [miroslavpejic85/mirotalksfu#5]
The iPhones safari don't seem to show the video feed.  Other users (non-iphone) can see the iPhone video and hear.  Audio works on the iPhone.  The iPad works, Mac works and windows 10 works.

- I tested mirotalk (none sfu) and the iphone works.
- I turned off the firewall just in case that was causing it.  That was not the issue either.
- What ports are required to be opened?

Noticed the whiteboard is gone for SFU.  Is there a reason?

Thanks,
IO

**Comment by miroslavpejic85** [comment]
Yes, you are right ... O.o 
And a first release, There is still work to finish it. 
Whiteboard and other stuff will be implemented.
Thanks

**Comment by miroslavpejic85** [comment]
Hi @ioscanner,
You should now be able to see the video streams correctly in IOS as well

commits:
- https://github.com/miroslavpejic85/mirotalksfu/commit/1e845cf87f057c61c98326a7001e9ab719387770
- https://github.com/miroslavpejic85/mirotalksfu/commit/6b871c9d7d8cbac43cd2c5195e7df15a4ea30884

Regards

**Comment by ioscanner** [comment]
confirmed match resolved the issue!  Thanks.  Also, audio seems to be in sync better.
