### ISSUE TITLE
there is a problem with mediasoup

### ISSUE THREAD

**Issue by Andrew-Sparrow** [miroslavpejic85/mirotalksfu#50]
### Describe the bug

after `npm install` there is error

[screenshot_1](https://i.imgur.com/0hiG0UD.png)
[screenshot_2](https://i.imgur.com/jZb5CW8.png)
[screenshot_logfile](https://i.imgur.com/T4C0lTQ.png)

 - Device or OS: Ubuntu 20.04
 - IDE - VSCode
 - npm - 6.14.16
 - node - 14.19.1
[screenshot with versions](https://i.imgur.com/y0gQV5Y.png)

**Comment by miroslavpejic85** [comment]
Hello @Andrew-Sparrow, 
From the logs I see that it writes `No module named pip` (sudo apt install python3-pip), which is one of the dependencies specified in the readme. To install mediasoup in addition to NodeJS and npm which is fine you must also have python3-pip DEB package, build-essential DEB package and python version >= 3.6 with `PIP`:

All the comands must be execute as sudo:

```bash
# gcc g++ make ...
sudo apt-get install build-essential

# Python 3.8
sudo apt update
sudo apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.8

# Python3 pip package
sudo apt install python3-pip

# Python3 setuptools
sudo apt install python-setuptools
```

You can also follow the steps to install it on ubuntu:20.04 in the docker file

https://github.com/miroslavpejic85/mirotalksfu/blob/main/Dockerfile

**Comment by Andrew-Sparrow** [comment]
@miroslavpejic85 thank you so much !

**Comment by miroslavpejic85** [comment]
You are welcome ;)
