### ISSUE TITLE
how to deploy mirotalk app on cpanel and how to change host url

### ISSUE THREAD

**Issue by Sanjay12333** [miroslavpejic85/mirotalksfu#51]
Hello sir,
mirotalk app working fine on my localhost but i have an issue when i deploy my app on c-panel its not working i am getting this error 
(node:213) UnhandledPromiseRejectionWarning: Error: spawn /home/nexever/public_html/mirotalksfu/node_modules/mediasoup/worker/out/Release/mediasoup-worker ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
please let me know where i am going wrong and also please let me know how can i change my app host url on live server.

**Comment by miroslavpejic85** [comment]
Hello @Sanjay12333, 
1. Make sure cPanel supports nodeJS and install all necessary dependencies for the project, and run the commands like sudo.
2. Configure firewall inbound rules correctly (rtc ports range, necessary for the audio-video stream)
3. On app/src/config.js change the announcedIp: 'cPanel IPV4 public IP'
4. Regarding (how can i change my app host url on live server) You must have a domain name and in DNS configurations you will need to create a type A record that points to cPanel IPV4 public IP.

For discussions - questions about deployments like this, please join with us on [discord](https://discord.gg/rgGYfeYW3N) on `help and support channel` or please read also the closed issue, you can find most of the answers there too. Thanks for understanding.

**Comment by Raj-nexever** [comment]
Hi. I tried your solution. changed announcedIp but not working.
is there anything that I need to change in other files?
server starts successfully but it shows error when I hit that URL in broswer?
this page can't be reached.

**Comment by miroslavpejic85** [comment]
No, make sure the point 2 are configured correctly, something like this:

|  Name |  Protocol  | Ports |  Destination |
|-----------|--------------|---------|-----------------|
| `MiroTalkRTC` | `TCP/UDP` | 40000:40100 | 0.0.0.0 |
| `MiroTalkSFU` | `TCP/UDP` | 3010  | 0.0.0.0 |

And also the announcedIp must be included between quotes `'.......'`

To reach it without a subdomain name that point to Your-Public-Static-IPV4, the URL should be something like: 
https://Your-Public-Static-IPV4:3010
