### ISSUE TITLE
Add gitpod to project

### ISSUE THREAD

**Issue by johan237** [miroslavpejic85/mirotalksfu#52]
I wish to add gitpod to this project.
Hello sir, I think git podifying(adding git pod to this repository) will be good for beginners who have struggles having all the dependencies on our computer.

I am suggesting this because I am walking through the repository aiming at contributing, unfortunately my laptop is not that strong and i can't all dependencies so I wanted to request you if I can add gitpod to this repo

**Comment by miroslavpejic85** [comment]
I replied to you in the forum on [discord] (https://discord.gg/rgGYfeYW3N) thank you for joining us.
