### ISSUE TITLE
How can I run the project on port 80/443?

### ISSUE THREAD

**Issue by DanielAbsi** [miroslavpejic85/mirotalksfu#53]
Hi I plan to self host the project on my own domain name on port 443 and 80. 
I was wondering how can I do it. I know that some ports have to ba change like port 3000 for APIs. 

Thanks for your help.

**Comment by miroslavpejic85** [comment]
Hello @DanielAbsi, 
You can change the port on app/src/config.js
However I think you talking about  [MiroTalk P2P](https://github.com/miroslavpejic85/mirotalk) (which use port 3000)
PS: Please join with us on [discord](https://discord.gg/rgGYfeYW3N) on help-and-support channel, it's the right place for questions like these, you may get answers there as well ;)
Many Thanks.
