### ISSUE TITLE
Not getting Other person video and Audio

### ISSUE THREAD

**Issue by Manishfoodtechs** [miroslavpejic85/mirotalksfu#54]
I am following the guide for installation mirotalksfu  on ubuntu20.04. I have valid fqdn with https. 
1. Tried on Ubuntu 20.04: No video and Audio of other person . But messages going.
2. Tried Docker too but same issue: No video and Audio of other person 
I have not changed any config in app/src/config.template.js. What I am missing?

**Comment by miroslavpejic85** [comment]
Hello @Manishfoodtechs, 
If you want to expose it outside to local network for test purposes, check out this: https://github.com/miroslavpejic85/mirotalksfu/issues/26
