### ISSUE TITLE
How to enable host function

### ISSUE THREAD

**Issue by Sanyam2007** [miroslavpejic85/mirotalksfu#55]
Hi @miroslavpejic85  can you please tell me how to enable host function with username and password

**Comment by miroslavpejic85** [comment]
Hello @Sanyam2007,
Copy `app/src/config.template.js` (configuration example) to `app/src/config.js` (this is the correct file from where MiroTalk reading the configuration) then edit `app/src/config.js` and restart MiroTalk.

```js
    /*
        Host Protection (default False)
        In order to protect your host set 
        hostProtected to true and set your own Username and Password
    */
    hostProtected: true,
    hostUsername: 'username',
    hostPassword: 'password',
```

PS: Join with us on [Discord](https://discord.gg/rgGYfeYW3N) on help and support channel for question like this ;)
Thanks.
