### ISSUE TITLE
Publish on docker hub

### ISSUE THREAD

**Issue by DarkDeddok** [miroslavpejic85/mirotalksfu#58]
Hey guys, could you please publish the image on docker hub?

**Comment by miroslavpejic85** [comment]
Hey @DarkDeddok,
It might be a great idea. Thank you for your suggestion. If you have pleasure join us on [Dicecor](https://discord.gg/rgGYfeYW3N), where we can talk about ideas like these. Thank you.

**Comment by alexanderadam** [comment]
@miroslavpejic85 is this really completed?
Where can someone find the official image on Docker Hub?

**Comment by miroslavpejic85** [comment]
@alexanderadam sorry, my mistake reopened and add in todo ;)

**Comment by miroslavpejic85** [comment]
## Official MiroTalk SFU Image

```bash
docker pull mirotalk/sfu:latest
```

## Note

The Free version of Docker Hub has limitations.

![DockerHubFree](https://user-images.githubusercontent.com/70838434/181474336-aa6547ab-751a-4581-9f17-f575b577db98.png)
