### ISSUE TITLE
iPad audio set to 0 when creating room

### ISSUE THREAD

**Issue by ioscanner** [miroslavpejic85/mirotalksfu#6]
When you create a room on an iPad the audio volume is set to 0.  When you click your video feed to change the volume level your video feed freezes and can’t be recovered until you logout and in again.

I have found that if you click any videos to zoom in and out the video freezes and you can’t get the video to start again.  It is stuck.  Tried to stop and restart the video nothing helps except exit and enter the room again.

**Comment by miroslavpejic85** [comment]
Hi @ioscanner,
Yes when click on video element he goes on full screen mode. Not have the iPad to test it, but I can put a button for full screen mode, in order to prevent this issue. This only happens to you on iPad, right?

**Comment by ioscanner** [comment]
Ok the patch for the video issue on iOS seems to have fixed this issue.  Now on iPad and mac you can expect to full screen and the video doesn't hang.  Also, audio seems to be in sync much better now.


Thanks
