### ISSUE TITLE
[Feature request] Extend API for password protected rooms

### ISSUE THREAD

**Issue by dannykorpan** [miroslavpejic85/mirotalksfu#60]
### Feature request

It would be great to extend the API for generating password protected rooms.

**Comment by miroslavpejic85** [comment]
Hi @dannykorpan, 
On default is disabled = 0/false, but now you can set a desired password for a room on direct join or api call.
Done: https://github.com/miroslavpejic85/mirotalksfu/commit/2a8cd5577cbe62dd60b64106ba52763c8b1d4071
