### ISSUE TITLE
localStorage mic choice will choose incorrect option if device disconnected

### ISSUE THREAD

**Issue by justincolangelo** [miroslavpejic85/mirotalksfu#61]
### Describe the bug

Storing preferences in localStorage by index (mic choice for example) will choose the wrong option if a device at a lower index is removed.

### To Reproduce

1. Connect multiple audio devices (internal speakers, headphones with mic, audio interface)
2. The options list may look like this: Beats Studio (default), Beats Studio, Scarlet USB Audio, Mac internal mic)
3. Choose the option at index 2 (Scarlet USB Audio)
4. Disconnect option at index 2(Scarlet USB Audio)
5. Reloading the page will choose the new index 2 (Mac internal mic)

### Expected behavior

Original choice is no longer available so we should use the default option at index 0

### Desktop - Mobile

Please complete the following information:

 - Device or OS: Macbook Pro OS 12.2.1
 - Browser Chrome, but others have the issue
 - Version 103.0.5060.134 (Official Build) (arm64)

**Comment by miroslavpejic85** [comment]
From [discord](https://discord.gg/rgGYfeYW3N), so I'm going to close it. Thank you for the feedback.

![localStorage-ok](https://user-images.githubusercontent.com/70838434/182449858-15dfb3a2-d189-4a35-b8d2-ba3ec4eef273.png)
