### ISSUE TITLE
Local participant muting

### ISSUE THREAD

**Issue by PalasX** [miroslavpejic85/mirotalksfu#64]
### Feature request

During a meeting, allow client to selectively mute the incoming audio from any of the other participants, but only mute it for themselves.

### Pros

Allows the user to mute/ignore a single meeting participant without hindering other's ability to hear them.
This can be useful if two participants are in the same physical space, and do not want feedback from eachothers audio source.
This could be a volume slider with mute option as well, in case there is one participant with audio coming in too loud for some reason.

**Comment by miroslavpejic85** [comment]
Hello @PalasX, 
It should all be implemented in the last commit: https://github.com/miroslavpejic85/mirotalksfu/commit/04c45b4b02d209bc325a37991b30e491962a9d5f
![handle-peers-volume-local](https://user-images.githubusercontent.com/70838434/184880655-901e78a3-3a7d-4dec-ac4f-77b0769f57a1.png)

**Comment by PalasX** [comment]
That looks great! I will pull the latest docker image and check it out later this evening.

Thank you for such a quick and responsive turnaround!!!
