### ISSUE TITLE
Sip & VOIP integration

### ISSUE THREAD

**Issue by Mirzahmet** [miroslavpejic85/mirotalksfu#68]
Hello. According to the tags, you indicated that there is Sip & VOIP integration. But I didn't find it in the code. Is he there?

**Comment by miroslavpejic85** [comment]
Hello Mirzahmet, 

Thank you for your interest in MiroTalk.

VoIP was born of a simple goal: facilitating audio (and video) exchanges via the Internet, thus improving connectivity between individuals in general. WebRTC arose from the same goal. In both cases, transmission happens in real time with one’s interlocutor, allowing true flexibility in the choice of equipment. In effect, any device linked to the Internet can potentially be used as a terminal: your mobile phone, desktop computer, tablet, smartphone, etc.
Location doesn’t matter, as long as you have an Internet connection.

SIP and WebRTC are both methods of VoIP as they both stand for real-time communications and look to send voice (and video) over an IP network (using the same standards/codecs).

Look at the tags in a bit broader view.

PS: I also replied to you on [Discord](https://discord.gg/rgGYfeYW3N), thanks for joining with us.
