### ISSUE TITLE
"WebRTC - SFU - Simple, Secure, Scalable Real-Time Video Conferences Up to 4k" , what is 4K users or Quality??

### ISSUE THREAD

**Issue by rahilparsana** [miroslavpejic85/mirotalksfu#69]
## Discord chat

Join with us on Discord and ask questions, create discussion, leave feedback.

- https://discord.gg/rgGYfeYW3N

**Comment by miroslavpejic85** [comment]
Hello @rahilparsana , Yes please for future questions join with us on discord. Thank you.
Regarding 4k, it mean up to 4k cam resolution, as for users, MiroTalk use mediasoup, you can read more about [here](https://mediasoup.org/documentation/v3/scalability/#multiple-and-separate-mediasoup-routers)
