### ISSUE TITLE
Screen share is broken

### ISSUE THREAD

**Issue by ioscanner** [miroslavpejic85/mirotalksfu#7]
Screen share is not working on Safari.  It opens, but you can't select the screen you want to share.   It is also running slow.  

Chrome works on Mac, and windows.

One other issue on iPad and iPhone the screen share button is present on safari?  It is not present on Chrome on iOS.

**Comment by miroslavpejic85** [comment]
- Screen sharing work on Safari, the reason of why you can't select a screen to want share is a Safari issue :)

- getDisplayMedia() is not supported on mobile devices, This is a limitation of the API itself. [Here](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia#browser_compatibility) you can see the compatibility.

- Regarding the video stream speed I put it on default to [15fps](https://github.com/miroslavpejic85/mirotalksfu/blob/main/public/js/RoomClient.js#L560) to consume less bandwidth, it usually runs on 30fps. You can change it, by you need.

Reagrds

**Comment by ioscanner** [comment]
Correct, I know screen share is not support on iOS devices.  But it still shows the Screen Share icon when on ipad.

Thanks I will play with screen fps.

**Comment by miroslavpejic85** [comment]
Done: https://github.com/miroslavpejic85/mirotalksfu/commit/4d7b57ccf60336d6af4f221cd1c65878ea46672f
