### ISSUE TITLE
nginx reverse proxy

### ISSUE THREAD

**Issue by alpha856** [miroslavpejic85/mirotalksfu#70]
Hello, when i want to use mirotalksfu with nginx reverse proxy, all things is OK and i can run subdomain  meet.XXX.com with SSL. but when i want to join any room, page not load and no things happen.  in other side, when i access to  mirotalksfu with direct ip and port, IP:3100 with self sign ssl, all things is OK and i can join any room. where is the problem?

nginx reverse proxy config : 

```bash
server {
    listen 80;
    server_name meet.DOMAIN.TLD;
    if ($host != "meet.DOMAIN.TLD") {
	return 444;
	}
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name meet.DOMAIN.TLD;
     if ($host != "meet.DOMAIN.TLD") {
     return 444;
}

    index index.html;
    ssl_certificate /etc/letsencrypt/live/meet.DOMAIN.TLD/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/meet.DOMAIN.TLD/privkey.pem;

    location ~ ^(/) {
        #add_header X-Frame-Options SAMEORIGIN;
        #add_header X-Content-Type-Options nosniff;
        #add_header X-XSS-Protection "1; mode=block";
        #add_header Content-Security-Policy "frame-ancestors 'none'";

        proxy_pass http://localhost:3100;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
    }
}
```

**Comment by miroslavpejic85** [comment]
Hello @alpha856,
Just follow [this documentation](https://github.com/miroslavpejic85/mirotalksfu/blob/main/docs/self-hosting.md). Please join with us on [discord](https://discord.gg/rgGYfeYW3N) for questions like this.
Thank you.
