### ISSUE TITLE
Support for simulcast

### ISSUE THREAD

**Issue by tangenttechno** [miroslavpejic85/mirotalksfu#71]
Simple question, Mediasoup has support for simulcast (adjusting bitrate against W.R.T client bandwidth).  Does the app support simulcast?

**Comment by miroslavpejic85** [comment]
Hello tangenttechno,

```js
        if (consumer.type === 'simulcast') {
            await consumer.setPreferredLayers({
                spatialLayer: 2,
                temporalLayer: 2,
            });
        }
``` 

Anything mediasoup supports can be implemented in MiroTalk.
Please, for future questions join with us on [discord](https://discord.gg/rgGYfeYW3N)
Thank you.
