### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by GrishinAV** [miroslavpejic85/mirotalksfu#73]
https://github.com/miroslavpejic85/mirotalksfu/blob/30bcfe93fae6d66b5b0dbe8013ec229b478db895/public/js/Room.js#L358

**Comment by GrishinAV** [comment]
function getRoomPassword() {
    let qs = new URLSearchParams(window.location.search);
    let roomPassword = qs.get('password');
    if (roomPassword) {
        let queryNoRoomPassword = roomPassword === '0' || roomPassword === 'false';
        if (queryNoRoomPassword != null) {
            return false;
        }
        return roomPassword;
    }

**Comment by miroslavpejic85** [comment]
Hello @GrishinAV, Fixed, thank you.
