### ISSUE TITLE
strange behavior is observed

### ISSUE THREAD

**Issue by GrishinAV** [miroslavpejic85/mirotalksfu#74]
Hello, I saw strange behavior. I create a locked room, and when I connect via ".../join/RoomName", i should enter password through the input field. 
But when I connect via, example,  ".../join/RoomName?password=1234&name=Name", then I was able to connect and change the password of the room to 1234.

**Comment by miroslavpejic85** [comment]
Hello GrishinAv, 
Yes, I noticed a bit of weirdnesses when using direct join. 
I tag it as a bug, then as soon as I have some free time I take a look at it.

**Comment by GrishinAV** [comment]
I think, for bug fix
https://github.com/miroslavpejic85/mirotalksfu/blob/f0c98e72047cc1e18d2af26841c3b5bb5cb9a0b1/public/js/Room.js#L699-L701
need to be moved in place after verification, maybe in function https://github.com/miroslavpejic85/mirotalksfu/blob/f0c98e72047cc1e18d2af26841c3b5bb5cb9a0b1/public/js/RoomClient.js#L283-L292

**Comment by miroslavpejic85** [comment]
Hello @GrishinAV, 
I found another solution on the fly: https://github.com/miroslavpejic85/mirotalksfu/commit/de6aa514e5b9b621e052caf251bda751c4d80090
Thank you.

**Comment by GrishinAV** [comment]
Now anyone, who connects to a non-password-protected room, can set a password by GET request.

**Comment by miroslavpejic85** [comment]
Try now it should be fixed: https://github.com/miroslavpejic85/mirotalksfu/commit/c72b7549b9b34344586e71e043eade5064604084
