### ISSUE TITLE
can not see other

### ISSUE THREAD

**Issue by parsibox** [miroslavpejic85/mirotalksfu#78]
hi
image from other client not show
what should i do?
![image](https://user-images.githubusercontent.com/12513476/197723196-f6802cc8-0ea9-4d5e-af00-3b9f805754c7.png)

**Comment by miroslavpejic85** [comment]
Hello @parsibox,

Please read also the closed issues - docs, before to open the new ones. 

Maybe join also with us on [Discord](https://discord.gg/rgGYfeYW3N) on `help & support channel` for question like this, Often you can find the answers there too.

Check out: https://github.com/miroslavpejic85/mirotalksfu/blob/main/docs/self-hosting.md in particular this part: 

<img width="636" alt="firewall" src="https://user-images.githubusercontent.com/70838434/197745898-b4d76c86-9f58-4c08-9f4d-668d22edcd45.png">

Thank you.

**Comment by parsibox** [comment]
thanks

**Comment by miroslavpejic85** [comment]
> thanks

You are welcome.
