### ISSUE TITLE
video is mirror

### ISSUE THREAD

**Issue by parsibox** [miroslavpejic85/mirotalksfu#79]
hi 
dear object in video is mirror
for example my right hand is on left side of video
how can change it?

**Comment by miroslavpejic85** [comment]
Hello @parsibox

Just search in the project for the `mirror` keyword.

![image](https://user-images.githubusercontent.com/70838434/197977682-5156e758-a729-4964-9572-ad8b5c7b5b9c.png)

However, it is absolutely normal behavior, it must be like this, for subsequent participants entering the room (mirror effect). Also try it on google meet, and you will have the same behavior.

As already repeated several times, join with us on [DISCORD](https://discord.gg/rgGYfeYW3N) for questions like these and not open issues here again :)

Thanks for understanding.
