### ISSUE TITLE
Request features from MiroTalk

### ISSUE THREAD

**Issue by ioscanner** [miroslavpejic85/mirotalksfu#8]
I would like to request these features from MiroTalk.

- File send
- White Board
- Raise hand

Thanks,
IO

**Comment by miroslavpejic85** [comment]
* Raise hand + possibility to turn off participants audio-video done here: https://github.com/miroslavpejic85/mirotalksfu/commit/a265f669b05f4c1372554a668e4a3c99e7b69f8b

**Comment by miroslavpejic85** [comment]
+ possibility to hide - mute - eject all participants in the room [here](https://github.com/miroslavpejic85/mirotalksfu/commit/d3761ad7d4e2eccf86700f3d86875dc7ec49faa0)

<img width="437" alt="mirotalksfu-all" src="https://user-images.githubusercontent.com/70838434/134304588-f54d82b2-7570-46c8-8e9e-f136937d9dad.png">

**Comment by miroslavpejic85** [comment]
- Collaborative Whiteboard done [here](https://github.com/miroslavpejic85/mirotalksfu/commit/5ce76141a36b3c3b051326c12cbd51568ca9ea2f) (Desktop-Mobile compatible)

![image](https://user-images.githubusercontent.com/70838434/134781264-bfc59bba-b8fc-46bb-a8f5-04dbaf401ce3.png)

**Comment by miroslavpejic85** [comment]
New Whiteboard functions done [here](https://github.com/miroslavpejic85/mirotalksfu/commit/6362f37ac42744ff4d10f83d4d2bb07ef03bd339)

![mirotalksfu-whiteboard-obj](https://user-images.githubusercontent.com/70838434/134816423-b008122b-0c1a-4e8c-a441-f5aa805a5c2c.png)

**Comment by miroslavpejic85** [comment]
- whiteboard: possibility to add the images from file or URL [here](https://github.com/miroslavpejic85/mirotalksfu/commit/16f2e9329c1dc1c02dd349a7fcc8c7c37ff16c7c)

![mirotalksfu-whiteboard-img](https://user-images.githubusercontent.com/70838434/134878622-f9331222-5852-41d6-b281-bfb02564dc18.png)

**Comment by miroslavpejic85** [comment]
- Whiteboard possibility to change background color [here](https://github.com/miroslavpejic85/mirotalksfu/commit/e398eb2bcdfa9ec72d472e7074b0528ae6a19b2a)

**Comment by ioscanner** [comment]
Great job!!  Looks we just need File share now!

**Comment by miroslavpejic85** [comment]
- File Sharing between peers in the same room, done [here](https://github.com/miroslavpejic85/mirotalksfu/commit/4f98a26d08de41824da046f2e8964e70f8bda5c4)

<img width="830" alt="mirotalksfu-filesharing" src="https://user-images.githubusercontent.com/70838434/135336120-daf91c4f-66a3-467d-a7f3-36abd4c29992.png">

<img width="845" alt="mirotalksfu-filesharing-done" src="https://user-images.githubusercontent.com/70838434/135336166-9f533d46-19fe-4126-8aab-df96f7b44ffc.png">

**Comment by ioscanner** [comment]
Perfect!  No issues tested on windows 10, 11, Mac OS, iOS devices 14.x, 15.x, and Android.

Only options left I can see would be useful would be.  Background blur, Noise cancelling and authentication option to create a new room. 

The new layout works and looks very polished now.  Great job!

**Comment by miroslavpejic85** [comment]
Thanks, yes, there are still some implementations - improvements to be made.
Regarding the main requests of this task, I think I have completed them all here ;)
