### ISSUE TITLE
mobile goes hot + mac os restarted

### ISSUE THREAD

**Issue by parsibox** [miroslavpejic85/mirotalksfu#80]
hi
dear i test with 2 mobile phone , samsung s21 ultra and samsung 20 fe 
these 2 mobile is not in a city ,they are in different city
both of  mobiles goes hot after about 3-4 min
also i test with a mac , after 1 min mac os restarted , i repeat it again with mac and it restarted again
what it the problem?

**Comment by miroslavpejic85** [comment]
Hi @parsibox,

Please join with us in the [DISCORD forum](https://discord.gg/rgGYfeYW3N) for questions like these, and see if anyone else has this issues. 

Personally I have meetings with long durations on Mac OS (several hours) and I have not encountered the problems mentioned.

Thank you.
