### ISSUE TITLE
set video and audio quality by peer speed

### ISSUE THREAD

**Issue by VladimirMbf** [miroslavpejic85/mirotalksfu#81]
First, Thank you so much for this great solution!

I'm getting troubles when participants have lower than usual internet connection, could be great to use for example ping to get a latency to server side and set quality by this latency value. Because zoom with the same participant working well, because it trying to apply some corrections in lower speed connections, I saw these changes in quality by video capturing. Could you tell please, what is the best way to resolve this issue?

Thank you so much in advance!

**Comment by miroslavpejic85** [comment]
Hello @VladimirMbf, 
Thank to you for your feedback, I'm glad you like it!

Try with set lower [video resolution](https://github.com/miroslavpejic85/mirotalksfu/commit/afba0c764a04bb33bd6f4b5d532661dc3d125534#commitcomment-91196016), in case of slow connections.

With that commit however, I also set it to take the default resolution of the camera, not the highest available like 4k... (I let the user set it if he wishes). Let me know if anything improves ;)

Join also with us on [discord](https://discord.gg/rgGYfeYW3N) - channel: `ideas and suggestions` where we can also discuss about it ;)

Thank you and have a good day.
