### ISSUE TITLE
Mediasoup install problem

### ISSUE THREAD

**Issue by hafeez-qureshi** [miroslavpejic85/mirotalksfu#82]
![Screenshot (3)](https://user-images.githubusercontent.com/78594395/206830685-9f4260f4-9db9-4fc9-9a66-75fe8da0d32e.png)

**Comment by miroslavpejic85** [comment]
Hello @hafeez-qureshi,

Just run `npm install`, it's not enough, as also specified in the readme, there are some dependencies to install first. Anyway [check this](https://mediasoup.org/documentation/v3/mediasoup/installation/#windows) and then subscribe also in the [official mediasoup forum](https://mediasoup.discourse.group), where is a search bar on top right, where you can find many answers, also this one related to installation in windows. 

Join also with us on [Discord](https://discord.gg/rgGYfeYW3N) for questions like this one, where also you can found many answers, without open a issues here.

Thank you and good week end.
