### ISSUE TITLE
Auto-detection of external IP

### ISSUE THREAD

**Issue by hoewer** [miroslavpejic85/mirotalksfu#87]
### Feature request

I would appriciate if your sfu-branch could gather the external IP (announcedIp) automatically. SOHOs often have dynamically assigned IPs - and it is quite annoying to adapt the configuration every time the IP changes.
For your other branches (c2c/p2p) Coturn (or other TURN-servers) are performing this job.
It would be either possible to use Coturns approach (using an external shell-script) or implement it via node.js.
For my purposes a poll when starting the software/container (I'm running it in docker) would be sufficient. However, it might also be useful to perform this every time a new room is set up.

### Additional context

Samples on the Web look like:
```
var http = require('http');

http.get({'host': 'api.ipify.org', 'port': 80, 'path': '/'}, function(resp) {
  resp.on('data', function(ip) {
    console.log("My public IP address is: " + ip);
  });
});
```

**Comment by miroslavpejic85** [comment]
Hello @hoewer,
If `announcedIp: ''` will be auto-detected now ;)
Thank you for your feedback!

**Comment by hoewer** [comment]
Thank you for your incredibly fast implementation. You don't have a life besides Mirotalk? ;-)It works like charm. BTW: Very nice project. I love it. I use it for family communications and prefer it to alternatives with commercial background or uncertain security .

**Comment by miroslavpejic85** [comment]
You are welcome! 
I work for a company full time, and maintain MiroTalk in my spare time :) 
I'm very happy to receive your positive feedback! 
Thank you and have a good weekend.
