### ISSUE TITLE
can't build docker instance

### ISSUE THREAD

**Issue by Phizicks** [miroslavpejic85/mirotalksfu#89]
### Describe the bug

docker-compose build fails with compile error from mediasoup-worker

[compose-error.txt](https://github.com/miroslavpejic85/mirotalksfu/files/10416825/compose-error.txt)

### To Reproduce

followed: https://hub.docker.com/r/mirotalk/sfu
git pull repo

cp app/src/config.template.js app/src/config.js
# also changed public ip to listen to.
cp docker-compose.template.yml docker-compose.yml
docker-compose pull # (tried without)
docker-compose up # -d

also tried raising version of node docker image to 18

### Expected behavior

container build correctly.

**Comment by miroslavpejic85** [comment]
Hello @Phizicks,

Thank you for trying MiroTalk!

Check out this doc too: https://github.com/miroslavpejic85/mirotalksfu/blob/main/docs/self-hosting.md

Join with us on [Discord](https://discord.gg/rgGYfeYW3N) - `help & support` channel, where you can interact with the community and also find many answers.

Thank you!
