### ISSUE TITLE
Pls help me

### ISSUE THREAD

**Issue by aarush-paul** [miroslavpejic85/mirotalksfu#9]
While I am using the command npm install, it takes forever to install and ends up bringing an error.
Pls help me out

**Comment by miroslavpejic85** [comment]
Hello @aarush-paul,
What OS & what an error it gives you?
Without some information, how can I answer you? :) 
As for the installation, it's ok, takes some time...

**Comment by aarush-paul** [comment]
@miroslavpejic85 yes im on wsl and this is the error
![image](https://user-images.githubusercontent.com/76874133/134149177-64c629ec-b8f5-4d5e-8694-bed9d5d10d4c.png)

**Comment by miroslavpejic85** [comment]
I'm Sorry, but it doesn't work on `Windows`, consider to installing WSL. This app work perfectly on Linux-Mac. For more details, you can ask question on official mediasoup forum regarding your question [here](https://mediasoup.discourse.group/)
Maybe someone has installed it on WSL...
Regards

**Comment by aarush-paul** [comment]
@miroslavpejic85 i tried on wsl too, but still didn't work

**Comment by miroslavpejic85** [comment]
As I said, you can find the [answers](https://mediasoup.discourse.group/t/install-fails-in-windows/458/9) 
So currently on Windows (WSL) it doesn't work. The best solution IMHO is to run it on `LINUX OS`.
Regards

**Comment by Jaideep25** [comment]
Nope, sadly, it needs a paid server~ Like Digital ocean, etc ;) You can check out the readme once 👀
Btw their are some issues or you can say bugs with the GYP project cuz of which it 1st won't support Python 3, and some Windows systems to (some exceptions are their, found on mediasoup 😜)

**Comment by aarush-paul** [comment]
Smh
