### ISSUE TITLE
Translation alternative

### ISSUE THREAD

**Issue by qiangweihewu** [miroslavpejic85/mirotalksfu#94]
### Feature request

Is it possible to add this translation extension project into your project's frontend or backend: 
https://github.com/immersive-translate/immersive-translate

Or, how to reverse proxy the google translation by myself?

Thank you very much!

### Pros

Google Translation has been completely blocked in China, so in usual way people can't access it.

**Comment by qiangweihewu** [comment]
Thanks for your reply and effort to make it work! I will try what you suggested.

**Comment by miroslavpejic85** [comment]
You are welcome!
