### ISSUE TITLE
 powerful app, but the image looks bad,what can i do?

### ISSUE THREAD

**Issue by yezhenhuitony** [miroslavpejic85/mirotalksfu#95]
Hello,
   I deploy this app on the server side, the functions are great, but the image is not clear, not smooth, and a little stuck. Is there any way to solve it? I test your Demo, The image is better then mine, but also not very clear, and when the person moves a little and it becomes blurred..  i test https://meet.jit.si/ ,the image is very good .
My Demo website: https://www.meetingme.cn:3010/ Please give me some suggestion?

Thanks

**Comment by miroslavpejic85** [comment]
Hello 

Seems you not followed all the [documentation](https://github.com/miroslavpejic85/mirotalksfu/blob/main/docs/self-hosting.md#nginx--certbot.) as I can see you still to have the port number at the end: https://www.meetingme.cn `:3010/` -  And as I can see, you not using the latest version from this repo.

Regarding the image quality can be set up to 4k and also the aspect ratio can be modified as you like as well form the settings.

# Video quality

<img width="475" alt="mirotalk-sfu-video-4k" src="https://user-images.githubusercontent.com/70838434/220839568-e20f032c-7148-4ee5-9a95-6eb1e62cce97.png">

# Aspect ratio

<img width="475" alt="mirotalk-sfu-aspect-ratio" src="https://user-images.githubusercontent.com/70838434/220839588-d9114f84-774c-4bf5-a0eb-bffcbad96b5f.png">

By default MiroTalkSFU producer/consumer type are [simulcast](https://bloggeek.me/webrtcglossary/simulcast/).
The quality of the call is proportional of your bandwidth in that moment...

Please for future questions like this join with us on [Discord](https://discord.gg/rgGYfeYW3N) - help and support channel, where you can ask to the community, get/find answers too.

Thank you!

**Comment by yezhenhuitony** [comment]
miroslavpejic85
  Thank you for your quick reply. I selected the video quality option of the menu, but the dynamic image effect is still poor. Maybe the problem comes from other reasons. I'm looking for it. Anyway, thank you very much.

**Comment by miroslavpejic85** [comment]
You are welcome! I did some improvements regarding webcam/screen-share encoding in the latest commits. Stay updated. MiroTalk will be improved ;) Thank you and have a nice weekend.

**Comment by yezhenhuitony** [comment]
Hello @miroslavpejic85

    I have reinstalled it with the latest docker image, and Configured SSL certificate and proxy forwarding on nginx. The test image is still is still  stuck, not smooth, and the image is not very clear. I also installed jitsi on my server. The jitsi test image is smooth and good. I embedded the JITSI web page into the login page. If you are free, please log in and have a look.  https://www.meetingme.cn      

![017](https://user-images.githubusercontent.com/95296844/222876061-c8d87db4-2e8c-4c2e-9357-be2ba62c4172.png)

Thank you very much

**Comment by miroslavpejic85** [comment]
Hi @yezhenhuitony,

`Without` even `increasing the video resolution` in MiroTalk (which you can set `up to 4k` - jitsi and `limited to HD`) I don't see [big differences](https://www.dropbox.com/s/devf80tbcjzabod/mirotalk-jitsi.mp4?dl=0)

Have a good weekend.

**Comment by yezhenhuitony** [comment]
hello miroslavpejic85:

     Sorry, I didn't describe the test clearly. The video at the remote is blurred and stuck, but the image at the local end is normal. I had send you a emil, The attachment is my test video of mirotalk and jitsi, using the same 1080P30 USB camera, mirotakl has been set to FULL HD quality at the far end. You can clearly see the difference, looking for your reply.

Thanks

**Comment by miroslavpejic85** [comment]
In [simulcast](https://bloggeek.me/webrtcglossary/simulcast/) mode this is normal (enabled by default for webcam), the video quality depends of connection bandwidth! As I said you can disable simulcast for webcam at all if you want. The producer with simulcast enabled sends 3 different layers (see it something like video resolution hight-medium-low) to SFU, the SFU based of endpoint bandwith sends the best layer for it. Some time the layer can be hight some time medium, some time low depends of participants bandwith.

**Comment by yezhenhuitony** [comment]
hello  @miroslavpejic85 
   If i set  enableWebcamLayers to false , When someone joins the meeting room, the remote video freezes immediately after showing. The local video is normal.
  I'm not sure if the change is correct, please correct me
 
![1678409947620](https://user-images.githubusercontent.com/95296844/224196564-96048a6b-7f61-40e4-80e0-bb80e6834532.jpg)

BestRegard
