### ISSUE TITLE
WHITEBOARD - Add text to clicked location

### ISSUE THREAD

**Issue by eduardogj** [miroslavpejic85/mirotalksfu#97]
It would be nice if there was a way to add text to a clicked location in the whiteboard. Having to click "add text", type in the text and then dragging it to the desired spot takes a long time.

The feature of clicking in a spot and a box showing up would be PERFECT for an online class in which we want the students to add text over an image.

**Comment by miroslavpejic85** [comment]
Hello @eduardogj,
Thanks for the suggestion, now you can edit the text when you click on it and move/resize it where/however you want.
