### ISSUE TITLE
Is it possible to install on Windows?

### ISSUE THREAD

**Issue by thangdalat** [miroslavpejic85/mirotalksfu#99]
If possible, please guide to install on Windows

**Comment by Bilal815** [comment]
Yes, it is possible to install it in windows. The instructions are in the ReadMe.

You need to have Python, pip, and Python's libraries. Also, you would need NodeJS and all dependencies that are needed for the application to run. Finally, you can run the app. Do let me know if you need further help. Thanks.

**Comment by thangdalat** [comment]
I run the command npm install then the following error occurs:
PS F:\THUNGHIEM\mirotalksfu-main\app\src> npm install
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142  
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path F:\THUNGHIEM\mirotalksfu-main\app\src\node_modules\mediasoup
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node npm-scripts.js postinstall
npm ERR! npm-scripts.js [INFO] running task "postinstall"
npm ERR! npm-scripts.js [INFO] buildWorker()
npm ERR! npm-scripts.js [INFO] installMsysMake()
npm ERR! npm-scripts.js [INFO] executeCmd(): C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\python3.exe worker\scripts\getmake.py
npm ERR! Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
npm ERR! npm-scripts.js [ERROR] executeCmd() failed, exiting: Error: Command failed: C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\python3.exe worker\scripts\getmake.py
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Local\npm-cache\_logs\2023-03-28T23_06_46_246Z-debug-0.log

Please help me fix the error, thanks

**Comment by Jaideep25** [comment]
Hey @thangdalat ,
It shows that you have not installed python on your OS.
Regards.

**Comment by thangdalat** [comment]
I have python version 3.10.4 installed. Check with the command PS python --version
PS F:\THUNGHIEM\mirotalksfu-main> python --version
Python 3.10.4

**Comment by Bilal815** [comment]
> I have python version 3.10.4 installed. Check with the command PS python --version PS F:\THUNGHIEM\mirotalksfu-main> python --version Python 3.10.4

Oh okay. Do you have anaconda on the system?

Is this on your IDE's terminal? It is probably your path for Python. Check this https://datatofish.com/add-python-to-windows-path/

**Comment by rickbraghetto** [comment]
I had the same problem, on windows python is installed in the Program files folder!! and this space between the name affects when installing dependencies, because it puts, C:/Program Files/.....
and the right thing would be C:/"Program Files"/... for cmd to read it correctly.. that's why you need to change python to C: for example in the C:/python folder !! and change the environment variables, then just be happy!!!

**Comment by miroslavpejic85** [comment]
Thank you guys for the support. I'm going to close, it seems resolved.

**Comment by miroslavpejic85** [comment]
Hello @Bilal815, 
Can you please write down the steps you did to successfully install MiroTalk-SFU on windows system? 
That would be great and very useful! Thank you so much for support the project.

**Comment by rickbraghetto** [comment]
@miroslavpejic85 Lets go !!! 

The master is working perfectly on windows!! https://github.com/miroslavpejic85/mirotalk !!!! however sfu is not running on all windows, I managed to run on windows server, however on windows 10/11 it is not running yet!!! however in case anyone has doubts, the mirotalk that is in the link above is running perfect just putting it in the folder and npm install then npm start !!!


![image](https://github.com/miroslavpejic85/mirotalksfu/assets/76504748/b440b7f1-53c0-4cb0-830e-ad5603785205)

![image](https://github.com/miroslavpejic85/mirotalksfu/assets/76504748/748507e5-5665-4419-b877-2b5fd0ce1564)

**Comment by miroslavpejic85** [comment]
>  the mirotalk that is in the link above is running perfect just putting it in the folder and npm install then npm start !!!

Yes I know that, I need if someone can write the steps on how to deploy successfully `MiroTalk SFU` on `Windows OS`.
Thank you!

**Comment by miroslavpejic85** [comment]
# Install MiroTalk SFU on Windows OS

The fast way to deploy it on `Windows OS` is to use `Docker`:

1. Install Docker for windows: https://docs.docker.com/desktop/install/windows-install/
2. Restar the PC and run Docker
3. Follow the steps Quick Start with Docker in the README.md

```bash
# Copy app/src/config.template.js in app/src/config.js IMPORTANT (edit it according to your needs)
$ cp app/src/config.template.js app/src/config.js
# Copy docker-compose.template.yml in docker-compose.yml and edit it if needed
$ cp docker-compose.template.yml docker-compose.yml
# (Optional) Get official image from Docker Hub
$ docker-compose pull
# Create and start containers
$ docker-compose up # -d
# To stop and remove resources
$ docker-compose down
```

<img width="1626" alt="mirotalk-sfu-docker" src="https://github.com/miroslavpejic85/mirotalksfu/assets/70838434/7c3870cf-9108-4bfa-9334-8825fcec837c">

**Comment by wajeeez** [comment]
Thanks for this tutorial I have completed this and now I can access the meeting at localhost 3000, Now I want to make it online so that I can use it over other devices. Guide me for this purpose I want to have this source code deployed by me for educational purpose which I share on demand.

**Comment by miroslavpejic85** [comment]
> Thanks for this tutorial I have completed this and now I can access the meeting at localhost 3000, Now I want to make it online so that I can use it over other devices. Guide me for this purpose I want to have this source code deployed by me for educational purpose which I share on demand.

Good! Feel free to reach out for any questions, assistance, or support on our [dedicated forum](https://discord.gg/rgGYfeYW3N). Thank you!
